### ISSUE TITLE
[suggestion] "overworld bubble" that cancels certain mechanics

### ISSUE THREAD

**Issue by Jackiecrazy** [TheCyberBrick/The-Betweenlands#1022]
Inspired by the fact that it's hard to progress in many other mods if you've selected BL as your primary base, what if the censer could burn something that'd reverse decay in its area of influence? It could be some kind of infusion that would involve uduriis (to give it some use), and when consumed or put in a censer (in this case it'd have a very small radius) will reverse select effects (mostly potion tainting and food rotting) in the player's inventory.

**Comment by Leirday** [comment]
That seems like a nice idea.

**Comment by TheCyberBrick** [comment]
But would that actually help to progress with other mods?
You'd be limited to the area around the censer, so vanilla/modded tools still wouldn't be that useful because BL is mostly exploration based.
For food, sure, you could build some farms with overworld crops, but it's not like food is sparse in BL once you get set up with some farms.

**Comment by PetasiGit** [comment]
I don’t think this will be something that gets added, and as Cyber said, it wouldn’t even be that useful. Gonna close this issue, sorry.
