### ISSUE TITLE
Gem Singer works strangely

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#1053]
Betweenlands version:
3.6.0

Forge version:
1.12.2 Latest Version 14.23.5.2847

Multiplayer --> Forge Server

Installed mods:
Betweenlands 3.6.0

Description of the problem:
Gem Singer doesn't work, I am in front of a gem ore or a Life Crystal Stalactite and I use the Gem Singer and it does not show the white flash (or white wave)

can it be for some video option that I have configured?
Can anyone else test if the Gem Singer works?

**Comment by ghost** [comment]
How strange, my old Gem Singer has broken, and for testing I have taken a new GemSinger from the creative and ... now it works!

**Comment by ghost** [comment]
Dont work again, I am in front of a 2 natural gem ores

**Comment by ghost** [comment]
It works strangely, sometimes, having in front of a gem ore (natural generation) the Gem Singer does not detect it. Other times (somewhere else with another gem ore) if he detects it.

**Comment by TheCyberBrick** [comment]
That's because it's random, it has always worked that way. Here's how the gem singer works in detail:
do 64 times:
   pick random chunk within 6 chunk range
   pick random gem type (i.e. aqua, crimson, green or life crystal)
   pick random ore with that gem type
   if that ore exists in chunk, mark it

Example: with a 6 chunk range there's 13x13 = 169 chunks. The chance for a single chunk with an ore to be checked with the same gem type and then be marked is 1-(1-1/169*0.25)^64 = 9%. So if you have a single ore in a superflat world expect having to use the gem singer ~10 times.  
In a normal world that's not as obvious because many chunks contain at least one gem or life crystal.

I might change it to check for each gem type in each chunk and then pick a random one that exists, like that it'll find gems more reliably. Maybe it should also only use durability when it marks an ore.
