### ISSUE TITLE
[1.12.2] Client crash on first startup after update

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#1066]
#### Betweenlands version:

TheBetweenlands-3.6.1-universal

#### Forge version:

2847

#### Singleplayer or Multiplayer:

Client Startup N/A

#### Installed mods:

https://www.curseforge.com/minecraft/modpacks/ancient-towncraft/

## Link to full crash log

Latest Log-
https://gist.github.com/ProsperCraft/d5e0bef217160e39bf27912ecdea1cb8
Crash Log-
https://gist.github.com/ProsperCraft/cf71a95baf0f0dd9e11d406628f452d1

#### How to reproduce:

Here is the previous unresolved link due to not having proper logs - 
https://github.com/Angry-Pixel/The-Betweenlands/issues/995

1. Install older version of Ancient TownCraft, then unlock the profile and update mods mods, and run it, the first time it crashes.

**Comment by Gunner76th** [comment]
This is because you have your instance installed in the c:\users\ path tree on a Windows 10 machine. You need to move your install to a different location such as c:\minecraft\twitch 
On Roguelike Adventures and Dungeons we have players who have this exact same problem and when installed as stated above it resolves the issue entirely. The problem is due to how OneDrive and Windows deals with finels in that folder path, and how windows in general treat modded Minecraft when running in System Folders (C:\users, C:\Program Files\, c:\Program Files x86) )

As a general rule, you should never use the default install location for Twitch (or any launcher that stores modpacks in any folder that is a system folder or starts with c:\users\) and instead set the path manually. 

Line 5 of your Latest.log explains that forge was unable to read the file during initialization, due to either Windows or OneDrive having locked the file.

**Comment by ProsperCraft** [comment]
Seems plausible..

And with 152 mods this is the only one that has a problem with it?

**Comment by Gunner76th** [comment]
> Seems plausible..
> 
> And with 152 mods this is the only one that has a problem with it?

The Betweenlands seems to be the most common mod to have issues with it yes. However this has been a known issue with modpacks since the release of Windows 10 and Oracle Java 8.  When Java 8 and Windows 10 first came out and met each other, UAC would violently kill the minecraft process resulting in an hs_pid crash due to an access violation. If you changed the install location so it was no longer in the c:\users\ path but didn't change anything else about the setup, it would work perfectly without issue.  

Now, why The Betweenlands keeps causing this crash I dont know specifically, but I can say we deal with crash from players daily on Roguelike Adventures and Dungeons by Dreams. I am one of his support staff members, as well as the community owner for Team IHOC. To prevent this issue, we tell everyone to either install all modpacks on a dedicated gaming drive, or in the folder 

c:\minecraft\client\%modpack name here%\ 

or something similar to this. This eliminates the issue of windows causing problems with it running from a system folder, and prevents OneDrive from causing problems as it is not a monitored folder. In fact we have dealt with this issue so much, we have specific instructions for setting up Twitch, GDLauncher (our preferred launcher for modpacks), AT Launcher, and MultiMC to avoid almost all common issues.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/d181fe8d5113bb00d22faae85e6584de

This always happens after I update the pack and run it the first time, then after that it is fine.

Here is a crash on my home pc, where the Twitch folder is located in C:\Games\

**Comment by TheCyberBrick** [comment]
Unfortunately this is still something beyond our control. Forge core mods are packaged into their own .jar file and then included in the main mod file. On start up, if the coremod files doesn't already exist, Forge extracts it from the main mod file and puts it in some subfolder in the mods folder. At that point none of our mod's code has even run yet. On some systems this seems to fail (or take too long?) and thus the mod can't load (because it doesn't and shouldn't run without the coremod file). Perhaps this could be reported to Forge, but as far as I know 1.12 is entirely unsupported now.
@Gunner76th has mentioned several plausible causes for this, and I can confirm that we've also had reports with the same issue being caused by OneDrive, although I can't find that issue anymore atm.
