### ISSUE TITLE
repeller crash

### ISSUE THREAD

**Issue by jedimoo** [TheCyberBrick/The-Betweenlands#1109]
#### Betweenlands version:

3.6.2

#### Forge version:

1.12.2

#### Singleplayer or Multiplayer:

singleplayer

## Link to full crash log

https://gist.github.com/jedimoo/95ec96389ed0f5b4bd38ad1d9ff9f4fa

#### How to reproduce:

1.i placed the repeller
2.i placed shimmerstone
3. as soon as i place byariis the game crashes

#### Expected result:

i expected it to work as intended

#### Actual result:

it crashed the game

**Comment by TheCyberBrick** [comment]
This is most likely caused by a faulty Intel graphics driver. You could try updating your graphics driver. However, I recommend you disable Betweenlands shaders in its config which should fix this issue and also because performance will probably be significantly lower with an intel integrated graphics card.
