### ISSUE TITLE
[SUGGESTION] The Floater

### ISSUE THREAD

**Issue by UnexpectedProton** [TheCyberBrick/The-Betweenlands#1121]
I posted this on the wiki a few weeks back, but nobody really noticed it. The Floater would be a new, very large passive mob similar to a dark, grimy butterfly. It would spawn rarely in all biomes. 

However, it would be immune to ranged damage until a " wound" was opened. This could only be dealt with a slimy bone harpoon, which would allow you to drag most mobs toward you. It would break after the attached mob died.

The Floater would drop Floater membrane and blubber. Blubber could be used to craft a sulfur lantern, which would emit light as well as driving away snails. The membrane could be crafted into a bow, or it could be used to create a slingshot, which could launch players, items, mobs, slimy bone harpoons, arrows, or even Draetons.

**Comment by Chiromaw** [comment]
I like your idea but the drops (and their uses) could have better implications.  Such as the membrane being an endurance upgrade to the Draeton ballon.  As far as the harpoon and slingshot: I cannot see how either could be used effectively.  The harpoon would supposably be useful against the floater, but why would you need to grapple mobs closer to you in addition.  With the fact that it breaks after a pretty short lived use, there wouldn't much incentive to craft it.  And I never find myself wanting to catapult items or entities to another location.

I posted an idea for a wisp lantern not too long ago that is in the same ballpark as your suffer lantern.  It would be similar to vanilla lanterns in crafting (wisp and syrmorite nuggets) and was for exterior light decoration.  However I like your mire snail repulsion idea very much; especially since mire snails will be updated to seek out your crops as a meal.  Maybe the floater could have some connection to Wisps whose drops grant you a sulfur or wisp lantern with that effect.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
