### ISSUE TITLE
(Suggestion) Make infenstation optional

### ISSUE THREAD

**Issue by catspajamas1789** [TheCyberBrick/The-Betweenlands#1126]
By optional I mean make it so that certain mob can be turned off, especially for those with entomophobia. I really love this mod but its really hard to play when I get covered in bugs, it completely freaks me out. Or atleast make the screen overlay of the bugs able to be configured. That would help A LOT.

**Comment by Chiromaw** [comment]
Rather than turning off a mob all together, I think adding an option to convert the infested (bug crawling) status overlay to something more simple would be a relatively easy thing to do.  Such as: a red boarder around the screen, an icon next to your hotbar, or maybe your hearts turn into small stationary bug icons a kin to the firefly item sprite already in the mod.  Shaking off the bugs would be indicated by each of your hearts returning to normal one by one, or the transparency of the icon/ boarder increases until it's completely gone.  There are many ways to make this feature more accommodating.  Great idea, it's too bad you're having a tough time with it.  Hopefully the devs add something soon.

**Comment by TheCyberBrick** [comment]
A while ago I made this resource pack that removes the overlay particles and the biting sounds, you can now download it from our curseforge project: https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod/files/3133141
