### ISSUE TITLE
A couple questions

### ISSUE THREAD

**Issue by YonathanYeager** [TheCyberBrick/The-Betweenlands#1146]
Betweenlands version:
3.7.1

Forge version:
14.23.5.2847

Singleplayer or Multiplayer:
Both, Forge

Installed mods:
Mods.txt file below.

Hello;
I have a few things I would like to ask about.
1: As far as I understand it, the betweenlands mod has a method/methods of drastically reducing the usefulness of tools, food, armor, etc that do not belong to the mod. I have tried and failed to find a way to add other mod's items to the list of things that are unaffected by the usefulness reduction- I do have craft tweaker, but my coding knowledge and comprehension is minimal at best.
Is there a way to add other mod items to the immune list?
For example, the Ice and Fire mod has Dread torches. Lit magically, I would like for them to not go out in the between lands. Another thing I would like to integrate from the Ice and Fire mod are their dragon bone and dragon steel weapons and tools. Made from dragon parts and magic, these, as far as I am concerned- would not be effected by the betweenland's diminishment- at least not nearly as much as vanilla items.

2: I love the sludgeon and the tower above it. I would love to have the ability to make and experiment with my own dungeons and puzzles! Would there be a way to get the moving walls and the specific dungeon doors with custom lock puzzles?

Attached Mods.txt file:
[Mods.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/5742400/Mods.txt)

**Comment by PetasiGit** [comment]
1) There are configs for both items that can corrode and torches that go out in the dimension, try using those.

2) You can’t use the moving walls, but you can place dungeon doors and set custom codes by sneak-right-clicking on the doors. 

If you have more questions like these, I would recommend you ask them in the discord server rather than making an issue here on github.
https://discord.com/invite/5RwFZgT57p

**Comment by TheCyberBrick** [comment]
You _can_ use moving walls by spawning them in via commands ("thebetweenlands:moving_wall"). However, they need to be spawned in a 5x5 frame (with empty inner 3x3) matching any of [these](https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12-dev/src/main/java/thebetweenlands/common/entity/EntityMovingWall.java#L58) blocks, otherwise they despawn immediately.

**Comment by PetasiGit** [comment]
> You _can_ use moving walls by spawning them in via commands ("thebetweenlands:moving_wall"). However, they need to be spawned in a 5x5 frame (with empty inner 3x3) matching any of [these](https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12-dev/src/main/java/thebetweenlands/common/entity/EntityMovingWall.java#L58) blocks, otherwise they despawn immediately.

Ah, I never did the 5x5 frame thing, only tried summoning them on a floor and they never worked.

**Comment by PetasiGit** [comment]
Closing as there has been no further response, hopefully we addressed their questions well enough.
