### ISSUE TITLE
Allow redstone torches to work in the Betweenlands/add Betweenlands-style redstone

### ISSUE THREAD

**Issue by rabbitscreams** [TheCyberBrick/The-Betweenlands#1149]
The torch dampening effect affects redstone torches, which makes it very difficult to make most redstone contraptions and doors. It would be nice to make the Betweenlands more redstoner friendly/add some Betweenlands redstone components

**a friend and i were bouncing ideas off each other with redstone torch ideas and came up with a few:**

_Bottled redstone torch: crafting a redstone torch with a dentrothyst bottle creates a bottled redstone torch. mostly the same as a redstone torch, but cant be placed on the sides of blocks, and is waterproof

Redstone sulphur torch: crafting redstone with a sulphur torch gets you a redstone torch that the betweenlands cant snuff out

Exclude redstone torches from the torch dampening rule: as redstone torches are just sticks dipped in redstone, it doesnt make sense for it to get "damp" as redstone torches were never hot in the first place_

**non torch related redstone components could include:**

_redstone spit: crafting redstone with sap spit makes redstone spit, a water-proof and sticky version of normal redstone that can go up walls and ceilings. a con of this is it's a bit similar to the redstone paste mod

dentrothyst bulb: crafting a bottled redstone torch with an item that could act as a filament (maybe an octine ingot?) creates a dentrothyst bulb, a lantern-like light source. can be turned on and off with a redstone signal_

even if redstone torches are exempted from the rule and none of these ideas make it in, it would make the betweenlands much more friendly to redstone!

**Comment by PetasiGit** [comment]
Redstone torches dampen by default, but can easily be changed to not do so via the config whitelist for torch dampening. The Betweenlands has no redstone equivalent for a reason, because it is not intended for heavy automation. If you're interested in having redstone automation capabilities in the dimension, I'd recommend playing [Into The Betweenlands, a modpack by Serious Creeper.](https://www.curseforge.com/minecraft/modpacks/into-the-betweenlands)
