### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1165]
The Amulet Slot page on the wiki says you can apply extra slots to tamed mobs by right clicking them with it (consuming 2 uses).  However, I tried several times on a friendly spirit tree, harlequin toad, emberling, and tamed chiromaw.  None of them accepted any more slots nor any additional middle gem amulets beyond the initial one I gave them.  I have keep inventory on, and my character has 3 slots with 3 amulets equipped, in case any of those details make a difference.  How do you do this?

Also, not sure if this is a glitch, but when crouch clicking a tamed chiromaw to change whether it sits on your head, hangs from a block, or fly beside you; it always de equips the amulet I had given it before it can be interacted with.  So my chiromaw effectively does not have an amulet equipped due to the hassle of having to de equip it every time.  Same question as above.

**Comment by PetasiGit** [comment]
The wiki is unfortunately inaccurate in this case (and it’s a bug, I believe), because currently you can only apply multiple amulets to a few utility mobs, not all of them. I believe it works with tar minions currently, and maybe one or two other mobs I can’t remember.

To keep amulets on your tame chiromaw while interacting with it, simply hold an item. Amulets only come off if you’re sneaking with an empty hand.

**Comment by Chiromaw** [comment]
thanks
