### ISSUE TITLE
Clients crashing randomly. VanillaFix is blaming TheBetweenlands 

### ISSUE THREAD

**Issue by aking4125** [TheCyberBrick/The-Betweenlands#1172]
At random intervals. Some users on our private server are getting a random crash. It doesn't seem to affect all players. Seems to only affect the players who entered TheBetweenlands. These crashes occur when simply returning to their base with teleporting methods like Waystones, /home, /back, JourneyMap Waypoint teleporting, the method really doesn't matter. 

The crash mentions:

 `at thebetweenlands.client.handler.CameraPositionHandler.getShakeStrength(CameraPositionHandler.java:42)`
 
 &
 
 `at thebetweenlands.client.handler.CameraPositionHandler.onClientTick(CameraPositionHandler.java:88)`
 
 We're at a loss as to what "exactly" is causing this. But the only thing we have to go on is that. I feel like there is more that we are missing but this is sadly all we have. Any ideas? Below is the client crash report.

[crash-2021-02-20_03.29.50-client.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/6015533/crash-2021-02-20_03.29.50-client.txt)

**Comment by TheCyberBrick** [comment]
This crash is most likely not caused by the BL as it also happens to some other mods when BL is not installed. Update Forge to the latest version if it isn't already up to date. If that doesn't help try without these mods because all related crashes I've found had them in common:
- codechickenlib 
- baubles 
- extrautils2 
- placebo
