### ISSUE TITLE
Suggestion: A couple of small ideas for the Draeton

### ISSUE THREAD

**Issue by TheElectroSheep** [TheCyberBrick/The-Betweenlands#1175]
Draeton Jukebox upgrade: A draeton upgrade which would allow one to play music disks while riding but with the caveat of increasing enemy detection range.
Perhaps capable of holding multiple disks to cycle through.

Draeton oars: I've found myself on occasion running out of fuel or losing all of my fliers, in this circumstance it would be great to be able to craft a pair of oars which the anchor upgrade could be swapped out for. This would allow one to traverse water with the draeton as though it was a boat without having the requirements of fliers or fuel.

Alternatively to the oars: A propulsion upgrade.
For if all your fliers are killed and you end up in water. An upgrade which reroutes your fuel to power a small putt-putt engine-like contraption to provide forward thrust in water at the expense of no lift for flying and slightly increased fuel usage.
Can be targeted and damaged by lurkers, causing the draeton to become harder to control and fuel to leak, just like when the balloon is attacked in the air.

**Comment by Chiromaw** [comment]
I think the jukebox and oars are great ideas.  I know a Draeton jukebox has been requested before, and the oars make sense due to the Draeton basically being a flying boat, and it would be good when you're stranded in water.  However I don't know about the propulsion idea.  1. although the Draeton should be able to have some water functionality, too much would make the Weedwood rowboat useless.  Moving through the water for instance, could make you susceptible to anglers that can rip holes in your ballon.  So it would be risky to use it over a rowboat.  2. the propulsion wouldn't make sense because shallow breath is supposed to be a helium like gas.  The Draeton is not equipped to create a high powered blast out the back, nor would it really be able to propel you forward too far with such a small vial of it.  Also same reason as before with adding to much water functionality.

**Comment by TheElectroSheep** [comment]
> I think the jukebox and oars are great ideas. I know a Draeton jukebox has been requested before, and the oars make sense due to the Draeton basically being a flying boat, and it would be good when you're stranded in water. However I don't know about the propulsion idea. 1. although the Draeton should be able to have some water functionality, too much would make the Weedwood rowboat useless. Moving through the water for instance, could make you susceptible to anglers that can rip holes in your ballon. So it would be risky to use it over a rowboat. 2. the propulsion wouldn't make sense because shallow breath is supposed to be a helium like gas. The Draeton is not equipped to create a high powered blast out the back, nor would it really be able to propel you forward too far with such a small vial of it. Also same reason as before with adding to much water functionality.

Ah, yeah propulsion thing makes sense. I was thinking that shallowbreaths are based around hydrogen and various toxic natural gases, which are usually flammable. So I was envisioning something which utilised the flame to create a sort of putt-putt boat effect with the water, which is why it wouldn't work in the air. I didn't really word my initial comment very well, did I?

**Comment by Chiromaw** [comment]
ok, I see what you mean.  But what use would the Weedwood rowboat have if the Draeton is basically the same thing with a boost ability?

**Comment by TheElectroSheep** [comment]
Same use it has anyway, to go and get more fuel when you run out! I find I use rowboats up until getting a draeton and then never again except for in emergencies

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
