### ISSUE TITLE
【Crash Report】ConcurrentModificationException

### ISSUE THREAD

**Issue by Phoupraw** [TheCyberBrick/The-Betweenlands#1178]
[crash-2021-03-05_00.20.22-client.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/6085159/crash-2021-03-05_00.20.22-client.txt)

All the details are in the crash report.

**Comment by TheCyberBrick** [comment]
This crash is most likely not caused by the BL as it also happens to some other mods when BL is not installed. Update Forge to the latest version if it isn't already up to date. If that doesn't help try without these mods because all related crashes I've found had them in common:
- codechickenlib 
- baubles 
- extrautils2 
- placebo
