### ISSUE TITLE
[Suggestion] Make the Item Scroll Weapons more unique.

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1187]
All of the weapons from Item scrolls work basically the same way. One shot a mob, otherwise be a very weak weapon. This is useful, but not very interesting. Instead, they should gain some other nonmagical special attributes to make them more viable. The Hag Hacker already has this, being both an Axe and having the swipe ability. For example, the Sludge Slicer, being a spear, could have extra reach. The Critter Cruncher could be made craftable perhaps, and the Wights Bane could also kill tar beasts. There are many possibilities, magical and nonmagical. These are just some examples.

**Comment by Chiromaw** [comment]
I agree with your sentiment, but I don't think any of them should be craftable.  Yes the hag hacker is taken care of, but the others could use some more uses.  Maybe the wight's bane can be thrown like a kunai like in one of the bl animations with the prime wight.  The critter cruncher already has so many uses when dealing with pests so that gets a free pass, and the sludge slicer could have more range and a stabbing animation.  These could all be upgrades that you craft onto the original item whenever the devs decide to add blacksmithing.

**Comment by spiderking23** [comment]
I kinda wanted some of the special abilities, ESPECIALLY the Reach for the slicer, to be passive, part of the original weapon. But I like the idea of adding some of the others via blacksmithing later. As long as they are unique to that weapon.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
