### ISSUE TITLE
MC Eternal Ring of Dispersion 1.12.2

### ISSUE THREAD

**Issue by ONIZeus117** [TheCyberBrick/The-Betweenlands#1191]
#### Betweenlands version: 
3.6.2

#### Forge version:
1.12.2

#### Singleplayer or Multiplayer:
Multiplayer

#### Installed mods:
https://www.curseforge.com/minecraft/modpacks/minecraft-eternal

## Description of the problem
Trying to make the Angel ring for creative flight and I need a Ring of Dispersion to craft it, I can't find it in JEI and everything i look up doesn't show how to get to the betweenlands.

**Comment by anabsolutesloth** [comment]
Go to a Swamp, find a Dark Druid Circle, kill them till you have all 4 Talisman pieces, shove them in the Dark Druid Altar, get the Talisman, right-click a Sapling with sufficient space around it, enter the Portal, find the Sludge Plains Clearing biome, do the Sludgeon, fight the boss, profit.
And also, please, for stuff related to MC Eternal, come our discord instead of yelling at the mod authors on github :p

**Comment by ONIZeus117** [comment]
I wasn't yelling at the mod author I was asking a simple question. I thought it wasn't in the game because it wasn't in JEI
