### ISSUE TITLE
[SUGGESTION] Weedwood Longboat

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1205]
The weedwood rowboat is pretty useful in early game, but once you break into other methods of transportation (toads, draeton, ring of scent, etc.) it becomes almost useless.  I personally even prefer the lurker skin shield for quick land/sea transition.  The next update with spear fishing has given me an idea on how to make the rowboats more useful.  I love how you can start with a basic rowboat, and upgrade it with a light and tar drip.  What if you could further upgrade the rowboat into a longboat using a crafting table and some additional materials.  The Weedwood Longboat would be slightly longer and wider than the rowboat, and function the same.  However, it would be a bit harder to maneuver around tighter areas.  Tar drip and light upgrades would also be carried over from the original rowboat.  The reason for the size increase would be so that when exiting the longboat, the player can actually stand up and move around in the boat while on water.  This allows the player to spear fish while in the longboat while also providing more protection from anglers than the regular rowboat.  Additionally, you could further upgrade the longboat by adding a fishing crate (or chest) to store supplies; and also a simple fishing line that can be cast to reel in any fish you pierced with the fishing spear so you don't have to exit the boat to collect them.  This fishing line could also be used to hoist crab traps to the surface to collect the caught crabs.  These upgrades would be applied just like the current boat upgrades once you have crafted a longboat.

Spear fishing without the boat is still possible, but you would have to go and retrieve the fish you caught every time.  Plus your movement is restricted in water.  The longboat would be perfectly equipped to be the ideal fishing scenario.  Not only would it add more late game functionality to obsolete rowboats, but it is also future proof; and will always be useful no matter how late in the game you are.

Crafting recipes:

Weedwood Longboat (crafting table)- Weedwood Rowboat in center space surrounded by Weedwood Planks.

Longboat Chest Upgrade (crafting table)- Weedwood Chest in center space flanked by Weed Rope, and sandwiched by Weedwood Plank Slabs.

Longboat Casting Upgrade (crafting table)- Reed Rope in bottom and middle rows (all 6 spaces) with an Angler Tooth in the top middle space.

**Comment by spiderking23** [comment]
I had a similar idea earlier. Instead of adding more to the Weedwood boat, why not add more boats with different advantages and functions? A Rubberwood Raft might be able to hold up to four people, a nibbletwig Canoe might be very fast and agile, and can be paddled in first person. A Hearthgrove Barge could be slow but maneuverable, and have storage onboard. Etc.

**Comment by spiderking23** [comment]
And maybe all of these could possibly have a Draeton version with different functions, appearance, and speed as well.

**Comment by Chiromaw** [comment]
I like the train of thought, but draetons would be very hard to create more functionality for outside of upgrades.  As far at the boats go, it would also be much harder (and a lot more work) to have several boats rather than one you can upgrade.  If you spread functionality among multiple assets, it makes each one more situational and trivial.  For instance: the rubber wood raft would be hard to implement because not only would having 4 players travel on water together be useless outside of multiplayer (and even then probably not); but the boat would have to be very large, and not be able to move into most areas that are not open water.  Plus, as I already said, there are so many ways we can traverse water without boats.  The purpose of the Weedwood longboat would not be for easier or more maneuverable travel, or even travel at all as it is outclassed in later game.  The purpose would be to make fishing easier so you don't have to dive underwater to empty crab traps, and fetch fish you skew with your spear.  I am still in favor of having a single boat with more functionality.

**Comment by spiderking23** [comment]
I agree with some of the arguments, but I feel like making boats out of the different woods would be beneficial to those woods general usefulness. Because Giant Roots, Nibbletwig Wood, and Hearthgrove Wood remain mostly... decorative outside of a few specific uses. (Sap wood excluded because it only drops sap) I feel like they need to be a little bit more useful seeing as an inexperienced player may want to use them for other things like tools, or boats, etc. I like the idea of a large storage barge, and the raft could have the benefit of being able to stand on it and fish instead of attaching the rod. And a Canoe would be very useful for traveling quickly, it would be a very fast, agile boat, and quiet too. Also, it would be nice if there could be multiple places to sit on these boats, for players or mobs. A Dinghy rowboat was traditionally made for around 4 people, so I feel some of these things could hold more than a single passenger. The bar be could have the advantage of right clicking it to kick mobs out of seats perhaps.

**Comment by spiderking23** [comment]
I dunno. I just want them to be more than fancy looking wood.

**Comment by spiderking23** [comment]
And I want more boats then the same one with different attachments.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
