### ISSUE TITLE
[SUGGESTION] The Ultimate Decoration Suggestion I

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1206]
Every item will be divided into smaller sections so watch out for that. Hex Codes will be put under some blocks because Im bad at describing colors. Note that all of the blocks are separate so if you decide to implement one of them then you dont have to add the others. Enjoy!

  Cotton
Cottontail plants would spawn in Coarse Islands biomes. They would be treated like any other plant item, but when right clicked with shears, they drop cotton and and become bare. They will regrow cotton eventually, similar to White Pears. Cotton can then be used to craft Cotton Blocks with 4 Cotton. Cotton Blocks will then act as a Betweenlands version of wool, allowing you to make carpets and banners.

  Compact Silt
Compact Silt can be found in large patches in the Betweenstone cave layer under patchy islands or can be crafted by 2x2 silt to produce 4 compact. This can then be crafted into Silt Bricks and its variants: Cracked, mossy, chiseled, pillar, tiles, slabs, stairs, and walls. The design could be similar to the quartz bricks in 1.16 and have a grayish-brown color. Chiseled Silt Bricks will have a carving of a silt crab on it to honor our great lords. Can also be crafted into shingles which have wider slats than mud shingles. HEX: 342824

  Hardened Peat
Hardened Peat would be made by smelting normal Peat. It would look like, well, hardened peat. Its hard to describe but Im sure you can figure it out. Hardened Peat could be turned into bricks, stairs, slabs, and walls. Chiseled Hardened Peat would depict the face of the Dreadful Peat Mummy on it. In the future, Hardened Peat can also be dyed. The dyed variants would be similar to terracotta in color. These can also be turned into their respective bricks, stairs, slabs, and walls. HEX: 201404

  Rune Shelves
In the future when Rune Weaving is implemented, there will probably need to be a place to store them. Judging by what we know they probably wont be able to stack, causing chest clogs. To solve this and the issue of lack of bookshelves, I suggest the Rune Shelf. The Rune shelf would have the same textures on all sides except the front. The front would have 3 empty shelves until they are filled. When you right click the Rune Shelf, it will open a GUI. There are 3 rows, each with 6 slots for runes. When runes are placed in the slots, they will also appear to take space on the shelf.

  Scabyst Bars
Its like iron bars but Scabyst, not much else to say.

  Dentrothyst Lamps
Dentrothyst Lamps would be made from 8 of their respective shard and 1 firefly. Green Dentrothyst Lamps have a 3x3 checker pattern while orange has something similar but tilted at a 45° angle.

  Glowing Pitstone
Glowing Pitstone would generate rarely in lake cavern ruins. It would have 3 glowing blue triangles in a line, the middle of which is upside down.

  Glowing Limestone
Glowing Limestone would actually be crafted instead of generated. 4 Green Dentrothyst, 4 Limestone Tiles, and 1 Sulfur would make 4. It would have 4 small glowing squares on each side of the block.

  Amate Item Frame
It works like a normal item frame and is made from Amate Paper and Weedwood Sticks.

  Weedwood Armor Stand
It is made from Weedwood Sticks and Betweenstone Slabs. It works like a normal armor stand. It also generates in the Sludgeon with Ancient Armor.

  Weapon Stand
A decorative block made from Cragrock. When right clicked with a sword or battleaxe the weapon will be placed handle up in it. Right clicking again will remove the weapon.

  Spirit Wood
Spirit Tree Logs can be made inti planks of a similar color. These can be made into slabs, stairs, etc. HEX: #443c2c

  Rubber Wood
4 Rubber Logs crafted together will make 1 Rubber Wood. It has the same texture as Rubber Logs but is the size of a normal block.

  Giant Root Leaves
Instead of Weedwood Leaves, Giant Root Leaves should spawn on Giant Roots. I mean theyre not Giant Weedwood Roots.

  Weedwood Slabs and Stairs
Slabs and Stairs made from the inside part of the Weedwood Tree.

  Reed Rope Fence
Reed Rope Fence would have a post in the middle made from Giant Root Planks. And connecting the posts are single Reed Ropes that curve down in the middle. They would be made from 4 Giant Root Planks and 1 Reed Rope.

  Sap Wood
When Sap Trees are broken they should not only drop Sap Balls but Sap Logs. This can be crafted into planks that have an orangeish brown color. HEX: D86D32

  Sludge Block
It looks like Sludge, it works like Sludge, but its a full block.

  Carved Wood
Either through a new utility block or a similar method to banners, Carved Wood could be made from logs of all types. It would have patterns like the Carved Rotten Wood in Sludgeons, but depending on the type of wood the patterns would have different colors.

  Reed Screen
The Reed Screen's shape would be similar to a glass pane or iron bars. It would have a screen made from Reed Rope surrounded by Giant Root Planks, like Giant Root Trapdoors but has a connected texture. It would be made from 5 Reed Rope and 4 Giant Root Planks.

  Hanging Bulbs
Hanging Bulbs are pretty simple. They would be Bulbcap bulbs hanging from Reed Ropes. There are two types, normal and triple. Normal had a single bulb hanging down. Triple has three smaller bulbs hanging down at different levels. They would be made from Reed Rope and Bulb Caps.

  Portal Wood
Wood from the Portal Trees should be treated like any other wood. Portal trees will now spawn with new inner-wood blocks and leaves instead of Weedwood. The leaves would be a greyish green while the wood would be similar to the bark. Gray planks could also be made from this. To make sure Portal Wood doesn't just come from Portal Trees spawned by the player, maybe a portalless variant could spawn in the PW's Realm. Planks HEX: ADADAD    Leaves HEX: 3C513C

**Comment by Chiromaw** [comment]
There is a lot here, so I will do my best to articulate my thoughts on most of your suggestions.

Overall I love the majority of these ideas.  The bl needs more customizable options when it comes to colors and some block variants.  First off, bl item frames and armor stands are planned, as well as some method of dye and dyeing wood/ other materials.  Though we have no information on it, sheep just told me they have plans for it.  I love the idea of the rune shelves.  They could work similarly to a pattern chest from tinker's construct, plus I really think bl should add more storage options more a kin to a cabinet.  Chests and shelves are great, but I always find myself needing cabinets.  In 1.16 vanilla, barrels work perfectly, but bl does not yet have an equivalent for that.  And the only shelves mod that is compatible with bl has outdated textures, and I just don't really like that mod too much.  I always prefer an in house feature opposed to an additional mod patching up a content hole.

No idea why you would need scabyst bars, the raw scabyst functions just like the bars, and it does not seem to be needed.

I like the idea of a weapon stand.  It would be awesome if you could display all the beautiful weapons the bl has to offer.  Having the ancient great sword, predator bow, and any of the mob specialty weapons would make a very nice assortment.  Added functionality to pick up and drop off anything you want would be great too.  Maybe it could also have a spot for rings and some misc. items like the bark amulet.  You could really create a very interesting and cool looking armory.  You could also place one near all your crafting and forging blocks for weapons you need to repair or are saving for a specific reason.  This feature will only become more useful once the devs eventually add a forging mechanic where you can upgrade and reforge armor and weapons.  Again, no info on it, just a mention on the discord by one of the devs.  They are looking favorably at it, and this stand idea could be a welcome addition.

Reed screen already kind of exists.  Amate Paper planes (made with Weedwood sticks and Amate Paper) function exactly the way you describe.  The texture does not involve reed rope though, but the 3 variants fit most needs.  Anything more you can create a custom texture pack.

Dentrothyst lanterns also tickle my interest, but they are less likely to be added.  They just recently added 4 new lanterns (one of them is glass).  So it is unlikely and would be very situational, only being used to match the palette of specific builds.  Plus dentrothyst would be way more expensive than Weedwood lanterns, so they would not be used for general lighting over their Weedwood variants.

As for the rest, they can be hit or miss.  I'm assuming the hardened peat would be the bl equivalent to terracotta.  I personally never have the need for that in bl, but I bet most would welcome the addition.  Sap wood would not work logically, as the whole point is that it would be very sticky and oozy.  Not ideal for structural integrity.  I support the request for weed rope fences.  Sludge blocks would probably act like slime blocks, but redstone aspects don't seem to interest the devs so I'm assuming no dice.  Hanging bulbs would be a nice decoration idea, not sure how widely it would be used though.  The devs do not plan to change anything about the portal tree to my knowledge.  And lastly, glowing variants of different stone types could be useful.  I never understood why each one didn't have it's own variant; but I never find myself using any of them other than the glowing betweenstone (the one that looks like a red stone lamp).  Great suggestions overall.  

Also, I understand this was all meant to be together; but in the future, if you can, the devs prefer suggestions to be more singularly focused.  In other words, don't have multiple different things in the same issue.  I assume it is so that if they resolve the issue, they can simply take it off the list.  But if there is more than one topic in an issue, then even if they check off one part, they still have to keep it open for the remaining.  That creates unnecessary clutter.  This is all in the same ball park, and it would arguably be an even bigger pain in the ass if you did like 15 different issues so your probably good.  Just thought I'd let you know.

**Comment by spiderking23** [comment]
A lot of this Sounds kinda nice, but Hardened peat? Peat is a kind of moss. You don't carve into it like that. I do like the idea of rope fences.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
