### ISSUE TITLE
[Suggestion] Varied Terrain.

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1221]
Let's all be honest. Most of the terrain in the betweenlands is the same. There are small hills, rivers, and in marshes, puddles of water. And that's really it. With t exception of Cragrock outcroppings every once in a while, it's all very much... Flat. So, my Proposition: a new Biome: The flooded Mountains! Composed of betweenstone and cragrock, these large stone formations grow out of the ground, which is composed of mud and water. There are lots of pools of mud and water on the rocky formation itself, and the plant life covers it like moss. That is, at lower altitudes. The higher it goes, there is more cragrock and betweenstone, and t he very peaks of the mountain are bare, without even ores touching the surface. But the difference between here and say, vanilla extreme hills, is the abundance of water pools, springs, and interestingly, there are bushes and stuff up here. And sometimes, smaller trees. Up here would also be a new mob, the Scarlet Osprey, a hawk-like bird with red feathers used to make magical arrows.

**Comment by spiderking23** [comment]
Other creatures found this high up might be some form of Climbing Species, perhaps rodents, or large cats.

**Comment by FirestarPlayz** [comment]
This would be awesome! Actual mountains in BL would look amazing. But Im pretty sure the reasons nothing is very tall are; first, swamps are generally flat (Or alteast from what Ive seen) Second, most of the world height is put underground so theres less room for fun on top.

**Comment by spiderking23** [comment]
Yeah, I know, but let's be honest, once you've seen a biome, you've seen every version of that biome. And a swamp is a damp, muddy area with lots of water. The altitude doesn't matter. Swamps don't occur in mountains because mountains are made of rock, but they can be surrounded by em. Along with these mountains, it'd just be great to see some legitimate hills every once I. A while, nothing large, but the varied terrain is just more natural and beautiful. Also, it makes PvP more interesting.

**Comment by Chiromaw** [comment]
Well I must say that the giant roots and the raised islands added some height to the terrain.  So height limit doesn't seem to be a problem.  Many of the raised islands are much taller than vanilla mountains/ hills.  I like this idea.  However, I think the concept needs to be more betweenlandsafied.  For instance, the sludge planes biome is basically locked off from you until you get rubber boots.  Maybe the mountains could be steep enough to require graphing hooks or some sort of new climbing gear to traverse effectively.  It would grant more use to graphing hooks, as they don't see much use as they are now.  Secondly, although birds and cats do live in mountains, they aren't very betweenlands-like.  Rather than birds and mammals; lizards, bats, and fish tend to be favored.  I think these mountains could contain something much more fitting.  We already have chiromaw matriarchs, but who do they mate with to get their offspring?  Chiromaw PATRIARCHS could reside in the mountains.  They could dwell in dens rather than nests, and rather than having offspring, they could hoard all sorts of ores, gems and treasures because of a fixation on shiny objects.  They would be much tougher than the matriarchs and have a more regal crown of barbs, and be slightly larger.  Perhaps the matriarchs could even acquire an AI that makes them occasionally fly to a patriarch den (or vice versa) for a mating season.  During this mating season, mountains would be much more dangerous to climb.  Mating seasons would rotate as if it were a weather event (though not weather related) and you could tell if it's a mating season either by crafting some sort of device to predict it; or maybe a special type of flower that grows on the mountain changes color when it is a mating season.  The other way this could be done is for the patriarch to fly to a matriarch nest for the mating season, leaving its stash unprotected.  This would be the best time to loot them, because of their extreme difficulty, and there is always the fear of them returning while you are in their den.  Chiromaw patriarchs could really be a beast to be feared patrolling the mountains.  They could provide a real late game challenge, making the mountain biome a sort of dungeon in its own right.  As for more common mountain mobs, there could be some sort of large frilled lizard that is adept at scaling steep walls.  Arial enemies could be some sort of large flying insect with a stinger.  You could still make those magical arrows mentioned before with the stinger as the bug's tip.  I am a little stumped on the mobs part (aside from the chiromaw patriarch) but there is a lot of potential for this idea.  I will post a more detailed issue on the chiromaw patriarch.  I have taken a liking to it after writing this.

**Comment by spiderking23** [comment]
I like the Patriarch idea. I do agree, cats don't really belong in Betweenlands, but Birds are very common in swamps, especially certain Birds of Prey and the different saltines to the herons and cranes. Ibis for example.

**Comment by spiderking23** [comment]
I figured this would be a great place to put the birds, and it gives a reason for the red feathers of the Magical arrows. (Which I think should have a base you make that is the only one that can be transformed)

**Comment by Chiromaw** [comment]
birds could probably work.  Like some sort of phoenix.  Cats wouldn't though.

**Comment by Chiromaw** [comment]
what do you mean by transforming base

**Comment by spiderking23** [comment]
A tower. A bridge. Getting places isn't too difficult most of the time. Unless you add a wind up that High, what's stopping me from just Building up the side of the Mountain?

**Comment by spiderking23** [comment]
And I'd do a less... famous fantastical bird. Like, I suggested a bird I thought would work very well. I have a few other bird ideas too, like a Heron, Crane, or Ibis (Ibis cause it sounds most exotic) though that would be for down in marshes, not up at the peaks.

**Comment by spiderking23** [comment]
Not transforming base, I'm talking bout the arrows.

**Comment by spiderking23** [comment]
Like a Base, as in Basic, the Base Component.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
