### ISSUE TITLE
[Question] Is there a need for two copies of every plant?

### ISSUE THREAD

**Issue by Mahoka** [TheCyberBrick/The-Betweenlands#1314]
As a new player to Betweenlands (encountered in Sevtech Ages), one of the more confusing/annoying things is that every plant has two separate items that can come from it: one from shears and one from the sickle. Example: Two items are named "Moss". One can be placed or composted, but not ground. The other can be composted or ground, but not placed. Is there a reason these have to remain separate? If they need to be to function, can both be grindable? If the purpose is to gate grinding with valonite, can the pestle just be made with valonite? Lots of inventory headaches having differing copies of the same plant.

**Comment by TheReaper501** [comment]
Getting into herblore requires at least a bit of exploring. Using the mortar + pestle is not exclusive to the herblore part of the mod; some items can be ground to get loot scraps or considering the new update, to get fish bait from tiny sludge worms.
The plant items that can be placed are this way because you can later replant and grow them with composted swamp dirt and meeting special requirements for some of them (placed underwater, hanging from the ceiling, against the wall and / or having a censer with bottled fog for them to grow), the plant items meant for the mortar cannot be placed, thus they cannot be renewed unless you got the placeable plant to regrow it.
Note: some plants, like Bladderwort flowers or stalks cannot be regrown, so you have to do a bit of exploring to gather them. The same stands for algae that float on top of the water. For the Sludgeon you can use both the placeable or droppable moss variant.

**Comment by PetasiGit** [comment]
>If the purpose is to gate grinding with valonite, can the pestle just be made with valonite?
There are other uses for the mortar and pestle, e.g., making ground dried swamp reed to grow plants with, so that specific suggestion would not work, unfortunately. Not sure about sevtech's progression, but we have lurker skin pouches to help with inventory management.
