### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SuperFeda** [TheCyberBrick/The-Betweenlands#1355]
Betweenlands version: 3.9.4
Forge version: 14.23.5.2869
Link to full crash log: https://github.com/SuperPypok/bllog
The game crashes while the game is running.

#### Installed mods:
![](https://cdn.discordapp.com/attachments/1014200166473023540/1066668170288582716/2023-01-22_173604.png)

**Comment by Andromander** [comment]
This issue happens when two dimensions share the same ID. In this case, the problem is a result of another dimension taking up Betweenlands's default dimension ID - 20. You can change it to another number in the config file and try again, but feel free to reopen if after changing it several times did not work.

To my knowledge, Aether and Twilight Forest don't clash with dimension IDs, but Advent of Ascension might cause conflicting IDs because I believe it adds several dimensions.
