### ISSUE TITLE
Farming system

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#155]
I am at a stage where I am very happy with these plans, but if anyone has any further suggestions please go ahead.

Firstly, compost is just crafted. I can add that bit.
Right click swamp dirt/grass with shovel --> dug swamp dirt/grass (there are two different textures)
Right click dug swamp dirt/grass with compost --> composted swamp dirt/grass
You can do the same with purified dirt.
Congratulations, you can plant shit now!

The crops need models but we can figure something out for now.
Purple Pear seeds --> Purple Pear Bush
Spores --> Yellow Dotted Fungus 

The purple pear bush grows in stages like the crop, but if you don't harvest it at a stage when the fruit is ready, it just dies and won't drop anything when broken. The dead crops will spread to other crops over time if nothing is done about it.

Yellow dotted fungus grows in stages, and when it is done, the small mushrooms on the crop will pop off on their own. If left too long the crop dies/decays and only Poisonous Yellow Dotted Fungus pops off.

To make purified swamp dirt less OP, plants planted on purified swamp dirt take longer to grow than on regular swamp dirt. I suppose we can put this down to the normal swamp dirt having more nutrients. This would also mean that plant tonic is still useful.

Crops can be revived using Dave's delicious patented Plant Tonic™, or if you use it on the plant at an earlier stage, they will last longer when they are at the 'ripe' stage. This stuff is just crafted, I can do that.

If you break a crop, for whatever reason, the composted swamp dirt/grass will turn back into swamp dirt. Composted purified swamp dirt will turn back into purified swamp dirt, but for 3 times.

One last thing. Swamp Reed Dust was going to be the equivalent of bonemeal, but since we have the Plant Tonic, it could perhaps only work on Saplings.

**Comment by vadis365** [comment]
Right click swamp dirt/grass with shovel --> dug swamp dirt/grass (there are two different textures)
Right click dug swamp dirt/grass with compost --> composted swamp dirt/grass

There is no point having the swamp grass variant  - seems silly to me if it has been dug.
Also I think the textures are named wrong.
Was going to start on this, but I'm a bit confused as to what texture is what.

**Comment by MrCompost** [comment]
There is a point, it just looks a lot nicer. If you were to dig swamp dirt, it would be weird to have the edges suddenly have grass, and if you were to dig swamp grass then it would become dirt. See this picture here (its the old version) http://imgur.com/H7GeDXK

As for the texture names, they aren't really named wrongly, just a bit weirdly.
The dug textures are called "dugPurifiedSwampDirt", "dugSwampDirt" and "dugSwampGrass".
The composted textures are called "fertDirt", "fertGrass" and "fertPurifiedSwampDirt". That's just how they've always been named.

**Comment by MrCompost** [comment]
Correct me if I'm wrong, but I think these bits need doing - 
"To make purified swamp dirt less OP, plants planted on purified swamp dirt take longer to grow than on regular swamp dirt. I suppose we can put this down to the normal swamp dirt having more nutrients. This would also mean that plant tonic is still useful."

"...or if you use it (Plant Tonic) on the plant at an earlier stage, they will last longer when they are at the 'ripe' stage. This stuff is just crafted, I can do that."

"If you break a crop, for whatever reason, the composted swamp dirt/grass will turn back into swamp dirt. Composted purified swamp dirt will turn back into purified swamp dirt, but for 3 times."

"One last thing. Swamp Reed Dust was going to be the equivalent of bonemeal, but since we have the Plant Tonic, it could perhaps only work on Saplings."

It would also be nice if there was a little digging particle effect.

**Comment by MrCompost** [comment]
Oh, and one last thing. I think a puddle destroyed my crops :P

**Comment by TripleHeadedSheep** [comment]
You shouldn't smear glue all over your crops... -_-

**Comment by vadis365** [comment]
"To make purified swamp dirt less OP, plants planted on purified swamp dirt take longer to grow than on regular swamp dirt. I suppose we can put this down to the normal swamp dirt having more nutrients. This would also mean that plant tonic is still useful.
--------------------
It's Hardly OP... vanilla farmland is OP - I look at it like the Stain of decay is removed and the crops can grow better NOT slower.
**********************
 "...or if you use it (Plant Tonic) on the plant at an earlier stage, they will last longer when they are at the 'ripe' stage. This stuff is just crafted, I can do that."
---------------------
Pointless FAFF! - The decay and other methods are on a random tick, not scheduled - to avoid more server lag...
**********************
"If you break a crop, for whatever reason, the composted swamp dirt/grass will turn back into swamp dirt. Composted purified swamp dirt will turn back into purified swamp dirt, but for 3 only times."
EDIT - What I meant here was that it remains as purified swamp dirt for 3 times, and then turns into regular swamp dirt, so they player will need to make some more
-----------------------
Sure - I just made it back to dug versions, but it wouldn't be difficult to change :)

**********************
"One last thing. Swamp Reed Dust was going to be the equivalent of bonemeal, but since we have the Plant Tonic, it could perhaps only work on Saplings."
EDIT - Ah, you added it to Dried Swamp Reed. It just needs to be Dried Swamp Reed Dust.
EDIT EDIT - Nvm, done it.
----------------------
Cool ;)
***********************
It would also be nice if there was a little digging particle effect. Also, I thought that the dirt would only become decayed when the plant stopped growing and died off. Atm it seems random.
----------------------
Okeedokee  Will do.

**Comment by vadis365** [comment]
This is done all bar the tweaks - make a new issue for the new crops when we have them sorted. :)
