### ISSUE TITLE
Dirty weapons/tools

### ISSUE THREAD

**Issue by TheCyberBrick** [TheCyberBrick/The-Betweenlands#157]
BL tools should have generally more durability than their vanilla equivalents, but they can get dirty/tainted. The strength/speed of the tools is lowered by a certain percentage depending on how dirty they are. The tools can be cleaned by putting them in the purifier.

**Comment by MrCompost** [comment]
I've done the texture, its called toolDecay. Add transparency if needed.

**Comment by MrCompost** [comment]
Another bar like item usage would probably get in the way and look a bit clumsy, so I would suggest having a tooltip that says stuff like "Good as new." "Slightly tainted." "Very tainted." "Extremely tainted." etc.

**Comment by MrCompost** [comment]
Make that decayed, not tainted.

**Comment by TheCyberBrick** [comment]
Make that corroded, not decayed.

**Comment by pau101** [comment]
What should cause an increase in decay? I'm thinking of it being a function of if the player's in water and the player's decay level. Thoughts?

**Comment by TripleHeadedSheep** [comment]
I think being in the water would be a cool thing for increasing the decay. And of course when using tools. I'm not sure what other aspects might be... maybe when using the items on certain mobs or blocks?

A cool thing to have is that the higher the player's corruption (or decay for that matter), the less your tools get decayed. This would be a cool thing to balance out the corruption. Because then your health might be less, but your tools are way more durable. Then players can choose when to play corrupted or not.
