### ISSUE TITLE
Shields

### ISSUE THREAD

**Issue by TripleHeadedSheep** [TheCyberBrick/The-Betweenlands#311]
With the shields added to Minecraft, we'd need some as well.
As I have no idea what the stats are of the current Vanilla shields, I'm not sure what stats I should give these, therefore I'll just rank them from weak to strong.
Here are some ideas:
- Rubber Shield
- Weedwood Shield _**Model Done**_
- Lurkerskin Shield _**Model Done**_
- Bone Shield _**Model Done**_
- Green Dentrothyst Shield _**Model Done**_
- Solid Tar Shield
- Syrmorite Shield _**Model Done**_
- Octine Shield _**Model Done**_
- Orange Dentrothyst Shield _**Model Done**_
- Valonite Shield _**Model Done**_
- Pyrad Shield _**Model Done**_
  ---
  
  Besides being normal shields, some of them could also have special abilities:
- Rubber Shield: 
  Entities bounce off of it, fun for SMP, can also catch fire
- Weedwood Shield: 
  Can catch fire
- Lurkerskin Shield: 
  Can be placed in the water as emergency raft (not very durable, nor very fast)
- Solid Tar Shield: 
  Especially useful against Tar Beasts, blocks their attacks. However, Tar Beast attacks use up more durability
- Syrmorite Shield:
  Can be used as some sort of SWAT shield. Charge it up (shift + right click?) and ram into your enemy. Does a great knockback
- Octine Shield:
  Reflects projectiles
- Dentrothyst Shields:
  Protects against any potion effects
- Pyrad Shield:
  Can only be found as loot item, works with the radial menu (so they don't really function as the normal shields). Player takes no damage when the shields are hit (they protect 3 sides). Also protects against wither effect.
  ---

Lastly, we could do something with adding a life crystal to your shield, which would heal you slowly over time (maybe only when actively using your shield). If a crystal is added, you can still recharge it, but you'll have to put in the shield itself, instead of the crystal.

**Comment by Sevenoon** [comment]
Here are the disadvantages that I believe each shield should have in order to make the shields fair.
- Rubber Shields should instantly blow up into flames when shot by Octine arrows
- Weedwood Shields should be the standard shield for the Betweenlands. Has a 50/50 chance of burning up
- Lurker skin Shields can be easily pierced by swords, arrows, and picaxes but shovels, axes and other materials have a 10% chance to bypass the shield. Feel free to change percentages
- Solid Tar Shields should give you a slowness II effect to mimic heaviness
- Syrmorite Shields ramming into a block will waste a lot of shield durability compared to ramming a mob/player. Ramming in general takes a lot of durability from the shield away
- Octine Shields should set the attacker's Weedwood weapons on fire or take a lot of durability from their Weedwood weapons. Octine shields are heavily weakened when in contact with water or during the Heavy Rain event
- Dentrothyst Shields easily shatter from melee weapons and arrows. Axes have a chance to break Dentrothyst Shields in one blow if combined with a critical hit. Dentrothyst shields greatly protect the player from both positive and negative potion effects
- Currently no ideas for the Pyrad shield

I also have an idea for the Life Crystal extension to the shield. If a Life Crystal is added, the Shield will circle the player in a slow circular motion automatically when equipped in the Radial menu. **_Feel free to change anything to your desire. Thanks!_**

**Comment by TripleHeadedSheep** [comment]
Those are some neat ideas. It's good you also think of the negatives ;)
Although, for now, I'd leave out any negative effects to the shields. Just to prevent it to become too complex.
The shields might get some special abilities, which the player could use to their advantage if they want to. But for those who don't really care, they can still stick to the standard weak-strong mechanic, where the Weedwood Shield would be weaker than, for example, the Syrmorite Shield.

If you were to add negative effects to the shields as well, you kind of force the player into the more complex system, even if they don't want to.
If that makes any sense...

Anyways, they are nice ideas to consider nonetheless, maybe for later? (As we are not even sure all the other abilities will be added)

**Comment by Sevenoon** [comment]
No, no, just take your time. I don't mind if you ditch some of these ideas or come up with new ones. Feel free to do whatever you want with these ideas. Thanks!

**Comment by TheCyberBrick** [comment]
The shields are already in with the basic blocking mechanics. The other abilities will be added later on in a feature update instead of with the port.

**Comment by vadis365** [comment]
old, old, old.
