### ISSUE TITLE
Duplicate Biomes

### ISSUE THREAD

**Issue by SylisMC** [TheCyberBrick/The-Betweenlands#325]
using minecraft 1.7.10, forge v10.13.4.1614, Betweenlands V1.0.6

Looking at biome ids that are in use. the betweenlands had 2 sets of biome ids.

50 & 178 Both Occupy by swamplands (thebetweenlands.world.biomes.BiomeSwampLands)
51 & 179  both occupy by coarseIslands (thebetweenlands.world.biomes.BiomeCoarseIslands)
52 & 180 Both occupy by deepWaters (thebetweenlands.world.biomes.BiomeDeepWaters)
53 & 181 both occupy by patchyIslands (thebetweenlands.world.biomes.BiomePatchyIslands)
54 & 182 both occupy by marsh1 (thebetweenlands.world.biomes.BiomeMarsh)
55 & 183 both occupy by marsh2 (thebetweenlands.world.biomes.BiomeMarsh)
56 & 184 both occupy by sludgePlains (thebetweenlands.world.biomes.BiomeSludgePlains)

the first set of numbers can be changed by the config file. but the 2nd set appears to be set in stone.
"Biome ID Limit"=false doesnt fix the duplicate ids, and setting the config files to 178-184 also crashes the game (with biome id limit on or off) because the the bioms conflict with themselves. (bc there are 2 of every biome)
ive tried removing the biome id lines from the config and also tried just leaving them blank, and ive also tried setting them all to 0 in hopes of the mod using the second set of numbers.

please fix this bug. its causing the game to take up twice as many biomes

**Comment by TheCyberBrick** [comment]
Nothing to fix here. That's vanilla adding biome mutations with the IDs "biomeID + 128". The biome ID limit was added intentionally because you **can't** use biome IDs over 128 without some nasty hacks.
If you want to know why: Biome IDs are saved as a byte and as such you can only use up to 256 IDs. If you were to remove that limit and save the IDs as an int it would break the world save files.
