### ISSUE TITLE
[Request] Allow anti-decay food items to be eaten even when full.

### ISSUE THREAD

**Issue by Shahelion** [TheCyberBrick/The-Betweenlands#335]
There are a few mods that disable or otherwise replace the hunger bar with something else, an example being Matter Overdrive's android state, which removes hunger entirely. However, this means I can't eat the things to reverse decay. 

Alternately, an additional anti-decay item that is drunk like a potion instead of eaten, which would still work for androids.

**Comment by TheCyberBrick** [comment]
There already is an elixir that heals decay, have a look at the wiki :P
Usually the decay items can still be eaten even if the hunger bar is full, it's probably somehow due to that other mod you mentioned.

Here's the elixir recipe: http://the-betweenlands.wikia.com/wiki/Infusions (it's the Elixir of Ripening)
