### ISSUE TITLE
Black Screen Issue?

### ISSUE THREAD

**Issue by INedonetimehelpsothisisbadaccount** [TheCyberBrick/The-Betweenlands#341]
I am having issues with a black screen. I have come across a closed post, that went over it saying that you have to disable BL shaders, or turn of Fast render. I have tried to turning off Fast Render, but it didn't work. i have no idea what to do now because i have no idea what BL shaders is (kinda a newbie, lol). anyone know what to do?

**Comment by INedonetimehelpsothisisbadaccount** [comment]
List of Mods in case you need it: Better Furnaces, Lucky Block, adventure backpack, BiblioCraft, carpenters blocks, Mo Creatures, fairy mod, Dynamic Lights (have no idea what this is lol) inventory pets, Minecraft Comes Alive, Mob Cages, Mr. Crayfishs Furniture Mod, Optifine, PetBat, Thermal Expansion, Xaeros World map, version is 1.7.10 btw

**Comment by theishiopian** [comment]
A couple of things:

1. No one can do anything to help you without a log. 

2. BL shaders is a feature of the betweenlands mod which enhances the mod's visuals via a shader, which is like a filter, but more advanced.

3. Dynamic lights allows items and mobs to cast light. If you are using the latest optifine, you don't need it because it is built in to optifine

**Comment by TheCyberBrick** [comment]
What @theishiopian said. If you have an Intel HD graphics card it's most likely due to broken graphics drivers. You can try updating your graphics drivers or finding out if it's caused by a mod incompatibility.
If that doesn't work you can just disable the shaders in the Betweenlands config file (if you're on Windows that's in %appdata%/.minecraft/config/thebetweenlands/config.cfg) and that should most likely fix your issue.
