### ISSUE TITLE
more black screen :/

### ISSUE THREAD

**Issue by Boter316** [TheCyberBrick/The-Betweenlands#343]
I saw another closed ticket with this problem but I have the most updated nvidia graphics drivers (as seen here: 
![2017-02-23 1](https://cloud.githubusercontent.com/assets/19333748/23256533/bd0196a4-f974-11e6-9529-df439208f4e9.png)
 ) and they were closed for not having a log so here's my log from boot, to problem:

http://paste.atlauncher.com/view/c4d0339e

(apparently the log was too big for pastebin, or here)

what I see 
![2017-02-23](https://cloud.githubusercontent.com/assets/19333748/23256690/71e2726e-f975-11e6-94c5-414c5cb98aac.png)

**Comment by TheCyberBrick** [comment]
I'm sorry, there's no way I'm going through an almost 10k lines long log x)
Since you have Optifine installed, make sure "Fast Render" is set to "off".
If that doesn't work you can disable the Betweenlands shaders in the config file and that will likely fix your issue, but with this many mods installed it's hard to tell what exactly is wrong.

**Comment by Boter316** [comment]
I apologize, I'm developing a modpack and got permission to use this mod in it so I'm trying to get it to work

**Comment by Boter316** [comment]
thank you, your second suggestion worked

**Comment by TheCyberBrick** [comment]
Cool, have fun!
