### ISSUE TITLE
[Suggestion] Add ability to change the block texture used for Druid Altar pillars.

### ISSUE THREAD

**Issue by TitusArmillius** [TheCyberBrick/The-Betweenlands#367]
I have found that changing the druid stone textures through a custom resource pack does not change the full textures, as only the side with the symbol uses the new texture, and the rest use the default stone texture.

I would be great if you could add a config option to set the block texture which the altar pillars use, as aesthetically the plain stone is difficult to accommodating into any sort of themed build around the betweenlands color palette and art style. 

here is a link tot eh custom texture I have wanted to use: http://www.mediafire.com/file/rjyfbu0c0n21yu6/thebetweenlands.zip

**Comment by TheCyberBrick** [comment]
Looks like you're using the 1.7.10 version.
Unfortunately we don't support that version anymore because it's too much work to maintain both versions

**Comment by TitusArmillius** [comment]
@TheCyberBrick I don't know what your talking about, I'm definitely using the 1.10.2 version.

**Comment by TheCyberBrick** [comment]
Oh, I don't see where the problem is then. You can edit the blockstates or block models, e.g. this one here:
https://github.com/Angry-Pixel/The-Betweenlands/blob/1.10.2/src/main/resources/assets/thebetweenlands/models/block/druid_stone_1.json

Just edit it and then put it in your resource pack like you would do with textures (different folders though)

For more information have a look at this: http://minecraft.gamepedia.com/Model
