### ISSUE TITLE
[1.10.2] FPS reduces when looking down in the betwwenlands dim.

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheCyberBrick/The-Betweenlands#368]
This inst really noticeable but it is for a sure a thing.

While on a render distance of 6-8, You barley notice but it sills lowers FPS.

If you put it higher you see a massive FPS dip while looking down, Now i know this isnt a huge concern but something im guessing underground is causing some FPS issues.

**Comment by TheCyberBrick** [comment]
Yeah, I noticed that too. My guess is that it's the mob spawners, will have to do some testing though.

**Comment by TheBritishBrotherhood** [comment]
Could be possible, The entity limit seems low thou. 

My second guess would be the spike things in the cavers, as iknow 1.10 rendering can be a laggy mess xD

**Comment by TheCyberBrick** [comment]
Nah I don't mean the mobs, I mean the spawner block.
I doubt it's the stalactites because those should be culled away and not rendered at all unless you're in the caves.
There was a bug in previous Forge versions where TileEntities wouldn't be culled, but that was fixed recently so make sure you're using the latest version of Forge and then check again.

**Comment by TheBritishBrotherhood** [comment]
Im using the latest version of the mod and forge :)

**Comment by purpleposeidon** [comment]
This is what the underground looks like in spectator mode in 2.0.4-alpha. _(Unless I'm messing things up with some other mod, which is totally possible.)_
![2017-10-15_19 15 10](https://user-images.githubusercontent.com/150333/31592459-449fa7a6-b1dd-11e7-879e-5f289e7bcb06.png)

It's like that pretty much everywhere.

If I stand at the threshold of stuff-get-culled, you can see that MC culls it all,
![2017-10-15_19 21 54](https://user-images.githubusercontent.com/150333/31592566-1f9be75c-b1de-11e7-9c91-c16572498ac7.png)
but sometimes fails.
![2017-10-15_19 21 33](https://user-images.githubusercontent.com/150333/31592559-14848dd8-b1de-11e7-8f50-69204202a88b.png)

In comparison, here's some vanilla cavegen:
![2017-10-15_19 24 30](https://user-images.githubusercontent.com/150333/31592630-877ef5c6-b1de-11e7-8316-7ef3f1ba2013.png)

Changing the chunk glDraw call to use GL_LINES should make it obvious if things not getting culled is a problem. You might be able to help it with the culling by dropping the caverns down 16 blocks so that they're at least a chunk-layer below the surface. This should make it super quick & easy for MC to cull. Then you'd just need to restore accessibility to the player by some means.

**Comment by vadis365** [comment]
Closing. A year old.
