### ISSUE TITLE
Modpack Redistribution Question

### ISSUE THREAD

**Issue by WesCook** [TheCyberBrick/The-Betweenlands#383]
Hi there,

I'm sorry for this possible abuse of the bug tracker, but you have comments disabled on the Curse page.

I'm reading your distribution terms, and it sounds like your mod may only be distributed on the Curse launcher.  Is that correct?  That would mean that users of the ATLauncher or any other alternatives aren't able to include the mod in packs.  As somebody currently building a pack in ATLauncher, that's really disheartening to see.

I'm just curious what the rationale is for limiting who is able to play with the mod.  I can't think of any reason for the exclusivity.  Could you please clarify?

Thank you.

**Comment by WightofShadows** [comment]
You are allowed to distribute on Curseforge without permission; in other cases it's okay as long as you have permission from us and give proper credit. This is the case because we've had multiple cases in the past where people use the mod to promote themselves without giving due credit. I'm not really in a position where I could really make the decision but get the attention of some of the other team members and I think they'll be fine with it.

Also, you can use our MCF post to comment in the future: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1441135-the-betweenlands-a-dark-hostile-environment-v2-0-0?page=5

**Comment by WesCook** [comment]
Hi Wight,

Thanks for your prompt response.

>This is the case because we've had multiple cases in the past where people use the mod to promote themselves without giving due credit.

I can understand this issue, and would feel the same way.  My question is though: why not write the distribution license to simply prohibit this sort of behavior?  This would avoid the issue of excluding other launchers altogether, and still make it clear what your position is on using the mod for promotion.

If your team would be willing to update your policy, I think this approach would make the most sense.

>Also, you can use our MCF post to comment in the future

Fair point, I hadn't considered the MCF forums.  Next time I'll head there first.

Thanks for your consideration regardless.

**Comment by WesCook** [comment]
The FAQ now includes this line:

>"Can I include the mod in my modpack?"
>Go ahead, so long as credit is given to the Angry Pixel team.

So I will presume the modpack policy has changed.  As such I'll close this issue.
