### ISSUE TITLE
Terrain generation failure with Geographicraft

### ISSUE THREAD

**Issue by PatientGhostwriter** [TheCyberBrick/The-Betweenlands#388]
When entering The Betweenlands while the mod Geographicraft is enabled, terrain generation fails near completely. Nearly the entire map is covered in water, and all the biomes are overworld biomes, in the exact same places as they are in the overworld. The player either spawns in on one of the very few islands in a spawn tree, or, more likely, deep underwater at the bedrock layer. The only land that generates is small, scattered dirt floaters under or at the surface of the water.

I'm not sure if it's more relevant to suggest here or towards the Geographicraft crew, but I was pointed this way from the forums.

**Comment by TheCyberBrick** [comment]
The BL pulls its biomes from a seperate list. Unless there's a biome ID conflict or another mod adds biomes via the forge event this shouldn't happen. Since the BL terrain generator is a bit different there might be some problems if a mod adds non BL biomes. 
~~Can you blacklist the dimension for that mod?~~
Ah, just read your MCF post. You should also report this to Geographicraft and that their blacklist doesn't seem to work.
Yeah, looks like Geographicraft modifies GenLayers which could cause this. Are you sure that you've properly blacklisted the dimension?

**Comment by Cakx** [comment]
I experienced the exact same problem.  The whole BL dimension is covered in water when Geographicraft is enabled.  Blacklisting the dimension did not help. My solution was switching to biometweaker. I'm just semi happy with that but this way there are no problems with BL.

**Comment by TheCyberBrick** [comment]
@BobtheLatinGuy or @Cakx did you report this to Geographicraft? I'm pretty sure that's a problem on their side since the Betweenlands only generates its own biomes unless another mod modifies the generator (which it should't if the dimension is blacklisted)

**Comment by PatientGhostwriter** [comment]
Yeah, I reported it to Geographicraft, but I switched from Geo to biometweaker before I got a reply back. It's the advice I'll give to anyone reading this in the future, too. If you're looking to use Realistic Terrain Generation as well, use the biometweaker example tweaks on RTG's forum post.

**Comment by TheCyberBrick** [comment]
Okay, thanks!
