### ISSUE TITLE
Dark Druids drop nothing if not killed by a player

### ISSUE THREAD

**Issue by Shahelion** [TheCyberBrick/The-Betweenlands#430]
Disregard if intentional.

**Comment by TheCyberBrick** [comment]
That was indeed unintentional, thanks!
Fix will be in the next version

**Comment by Shahelion** [comment]
It seems it has now been reversed. Using a TiCon Sword or TiCon Shurikens has it drop no talisman pieces, but it drops one every time when using Botania's Rod of the Unstable Reservoir, which currently does not give player kill drops.

**Comment by TheCyberBrick** [comment]
~~The responsible code hasn't been touched since then. Keep in mind that there's a 50% drop chance.~~
Nmv misunderstood what you wrote. Are you 100% sure? When I tested it everything worked. If the mob is not killed by a player it has a 50% chance to drop one of the 4 pieces. If it was killed by a player it has a 50% chance to drop one of the 4 pieces that the player does not yet have in the inventory, and if the player already has all 4 it can drop any of the 4 pieces.

**Comment by Shahelion** [comment]
It's very possible I just have extremely shitty luck.

**Comment by TheCyberBrick** [comment]
I've just tested it with the latest version and it's working as intended for me (with TiCon weapons too). The 50% chance to drop a piece should be there no matter how it was killed. If really nothing ever drops for you then another mod is messing with the drops.
Feel free to open a new issue if can figure out what's causing it for you.
