### ISSUE TITLE
Betweenlands does not behave well with a chunk pregenerator

### ISSUE THREAD

**Issue by Sunconure11** [TheCyberBrick/The-Betweenlands#437]
Granted, I'm using a rather beefy pack, but I keep encountering this every time I try to pregenerate my world (overworld, specifically) using the chunk-pregenerator mod:

https://pastebin.com/mxk6PYVz

**Comment by Oxosorrel** [comment]
It may have something to do with the way chunk-pregenerator does its fog of war thing... try the full pregen, which seems to work... you will need to pass the flag 'PostProcessing' to the command.

Example
/pregen startradius 0 0 100 ~ PostProcessing

**Comment by TheCyberBrick** [comment]
~The BL expects a chunk to have been loaded when it is saved which is usually always the case. The chunk pregenerator probably doesn't load chunks while generating and then directly saves them. I'll probably simply replace the exception with a warning instead.~
Actually this won't work so I won't remove the exception. What Oxosorrel suggested is a better solution if it works.

**Comment by Sunconure11** [comment]
I tried post-processing while in the world, but the server lagged to death before I could get any useful info.

**Comment by TheCyberBrick** [comment]
I would expect the server to lag when generating a ton of chunks, what's unusual about that? Isn't the point of the pregenerator to generate a bunch of chunks **before** playing so that later on the server doesn't have to generate the chunks while playing? Please correct me if I'm wrong, haven't used that mod myself.

**Comment by Sunconure11** [comment]
Er, I had tried the command within the game itself to see if that would solve this issue, and the server ate up all 8 gigs of ram it had. I am running it again, to see the results. So far, it hasn't crashed.

Edit: Post-processing delayed the crash a bit, but it happened in the end. https://pastebin.com/XtrssYW4

**Comment by TheCyberBrick** [comment]
Hmm ok, I'll see what I can do. As it is now I can't just remove that exception because other stuff would break and our world locations wouldn't generate properly. It might work if I make it use the new forge chunk capabilities that we didn't have in 1.10.

**Comment by GoryMoon** [comment]
Forge have a builtin pregen now that you can test, the command to run it is this:
/forge generate x y z chunkCount [dimension] [interval]

**Comment by Sunconure11** [comment]
Looks like that command works

**Comment by Speiger** [comment]
@GoryMoon if you do a forge 40k chunks process (1600blocks in each direction) that will eat up another 7GB of ram (based of 0,5GB start usage) and if it crashes in the process 90% of the data is lost.
Also @Sunconure11 this incompatiblity should fixed with the 1.6 version that comes out soon.
In general there should be much less issues. Because the logic is doing less funky stuff to try to prevent these things.

Next time please if there is a issue with my  command causing a crash with a mod come directly to me, that i can fix these kind of issues in the first place, and not find out of these at 75% of the development.


Also @TheCyberBrick you can close that issue since it is my bug not yours, and also it will be patched with the next version.
Edit: If a chunk saves or unloads and its not present in your data bank i would suggest not throwing errors and just ignore it, since that can have also its own set of problems. Since Entities that get created in a chunk get automatically spawned and if the chunk loads again you get a lot of thrown errors or crashes (depends on the MC version), now that is not a requirement to fix this issue but its 1 out of two ways. I am going to implement the second way for further versions.

@Sunconure11 please PM me on curseforge or discord or reddit (what suits you best, username is unified on all these platforms).
I want to make sure that issue is fixed.

Thanks for reading Speiger.
