### ISSUE TITLE
Hag Hacker, Sludge Slicer, and Critter Cruncher should function according to their appearance

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#459]
At least for Hag Hacker, it shouldn't have a sweep attack and should behave like an axe, disabling shields.

Sludge Slicer and Critter Cruncher aren't too clear as to what they are, but they're definitely not swords of any type. You could say this issue applies to Wight's Bane as well, but it's close enough to a sword (looks to be a dagger) to not really matter.

**Comment by TripleHeadedSheep** [comment]
They are specialised weapons that you can find as loot. They are very effective against their respective targets (hags, critters, sludges, and wights).
Since none of these mobs use shields, and since these weapons are not very effective against other mobs or players, In fact, I would say the sweep attack would be preferable here
I don't see a problem here.

**Comment by PetasiGit** [comment]
Just a matter of preference and consistency with the vanilla weapons. I'd think at least Hag Hacker would act more like an axe than a sword, since that's what the texture depicts.

**Comment by WightofShadows** [comment]
These weapons have always been considered swords, as even the Hag Hacker doesn't chop wood more efficiently the same way an actual axe does. I admit though, it would be interesting to see varying purposes for each weapon. I'd consider this more of a suggestion than an issue.
