### ISSUE TITLE
Request: Configurable Biome IDs

### ISSUE THREAD

**Issue by ddelaparte** [TheCyberBrick/The-Betweenlands#488]
Encountering biome ID conflicts adding your mod. Cannot change the other mod's ids without hosing worlds and yours are not configurable.

Please add overrides for biome IDs to the config file.

**Comment by WightofShadows** [comment]
Ours should be configurable. You sure you checked the config fully?

**Comment by TheCyberBrick** [comment]
~~Just a suggestion, what about not ignoring the issue template?~~
Never mind that, my bad. But we'd still need to know what version you are referring to
If you are talking about the 1.10+ versions,biome IDs can no longer be configured because they are handled by Forge's internal registry.
(Edit: As clarification, the 1.10 versions mistakenly still have biome ID entries, but they are not used anywhere)

**Comment by ddelaparte** [comment]
I use Open Terrain Generator in 1.12 which replaces vanilla generation. Not sure if that's the reason but I definitely have biome IDs and conflicts. I had to adjust OTG's Biome Bundle's IDs to get it working with Twilight Forest.

**Comment by TheCyberBrick** [comment]
Hm ok I guess I'll reopen this for now.
There shouldn't really be any biome ID conflicts because Forge assigns those now (just like block and item IDs), unless maybe if the game runs out of IDs (there's still only 256 IDs). Could it be that the manually assigned IDs from OTG's Biome Bundle override the BL biomes' IDs?

**Comment by TheCyberBrick** [comment]
If you give me a list of the mods that conflict and their versions I can try it out myself and see if we can do something about this

**Comment by ddelaparte** [comment]
I'm thinking it's a problem on OTG's end. They don't use Forge's ID assignment and instead hard-code the biome IDs based on configs. What's more, other mods and Forge don't seem able to "see" OTG's biomes - BiomeTweaker's report doesn't include any of them. So when other mods go to get their automatically-assigned IDs they aren't taking into account the ones already used by OTG.

OTG and Twilight Forest also experience ID conflicts.

**Comment by ddelaparte** [comment]
You can reproduce the results with OTG, Biome Bundle and Betweenlands installed together.
https://github.com/PG85/OpenTerrainGenerator/issues/128 is the issue I opened on their tracker.

**Comment by justinrusso** [comment]
Ive run into these type of issues multiple times now with mods that seem to have been ported to newer versions, but haven't really been updated to the "proper" way to do things in new versions. I have a map mod that uses the numeric id of a biome as well, its quite frustrating. To me, this is definitely on OTG. Betweenlands is doing it the right way.

**Comment by vadis365** [comment]
Closing due to other mods doing things in an outdated way isn't really our issue.
