### ISSUE TITLE
Draconic Evoution Pig Soul Item Causing Mipmap Flicker

### ISSUE THREAD

**Issue by MastrPancake** [TheCyberBrick/The-Betweenlands#522]
#### Betweenlands version:

3.3.1

#### Forge version:

14.23.2.2611

#### Singleplayer or Multiplayer:

Both Singleplayer and Multiplayer.

#### Installed mods:

Draconic Evolution 2.3.10.284

#### How to reproduce:

looking at the Pig Soul item in the inventory or jei.

#### Actual result:

Mipmap starts flickering in world. Requires restart to fix.
I'm guessing this happens because this mod may edit how entitys are displayed in the inventory. I found this when making a mod pack and narrowed it down by adding mod in and out until i found what was causing it. All other mods did not cause this until The Betweenlands was added.

#### Pictures:

https://gyazo.com/f731e6faa469c4dc91c4ebf2f502f69d (quality is bad but you can still see some flicker at the end)

**Comment by TheCyberBrick** [comment]
I can't really fix the root cause of this because DE/CodeChickenLib changes the item renderer and renders entities in items where the game doesn't expect it. But I can partially fix it so that it usually doesn't happen. I don't know how exactly that Mob Soul item works, but if it renders an entity with a Betweenlands Middle Gem (if that is even possible) there's a chance it could break again.

**Comment by MastrPancake** [comment]
Would it be possible to have a config option to blacklist items from being registered with a Middle Gem?

**Comment by TheCyberBrick** [comment]
I don't think there's any point in adding that. Only a few Betweenlands mobs naturally spawn with those, and while they can technically be applied to any mob it'd need to be done using commands.
