### ISSUE TITLE
Unable to connect to the server. java.lang.NullPointerException 	at thebetweenlands.common.network.clientbound.MessageSyncChunkStorage.handle

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#546]
#### Betweenlands version:

TheBetweenlands-3.3.4-universal

#### Forge version:

1.12.2  2635
#### Singleplayer or Multiplayer:

Multiplayer
#### Installed mods:

https://minecraft.curseforge.com/projects/ancient-towncraft

## Link to full crash log

https://gist.github.com/ProsperCraft/89590669a6684a185cd86f00abaccb56

#### How to reproduce:

1. Connect(server is in the modpack already) 
2. - fail, fail, get in and get kicked, fail, fail, connect and get in.

**Comment by TheCyberBrick** [comment]
I don't think this is specifically related to the Betweenlands because some vanilla code is also throwing exceptions in the log you sent, and whatever is happening shouldn't happen in the first place.
However, I've already added a workaround/fix to the dev version so it *should* be fixed in the next update.

**Comment by TheCyberBrick** [comment]
A new update is out with the "workaround". I don't think it'll help, but it's worth a try
