### ISSUE TITLE
TombManyGraves - Rings, Lurker bags and maybe other items drop on the ground

### ISSUE THREAD

**Issue by 3jlowes** [TheCyberBrick/The-Betweenlands#557]
#### Betweenlands version:

Latest
#### Forge version:

Latest
#### Singleplayer or Multiplayer:

The problem happens in both Singleplayer and Multiplayer. Vanilla Forge (no sponge etc.)
#### Installed mods:

Sevtech: Ages 3.0.4
https://minecraft.curseforge.com/projects/sevtech-ages

#### How to reproduce:

1. Install TombManyGraves with betweenlands
2. Have rings or lurker bag equipped
3. Die
4. Return to grave
5. All items except ring and lurker bag inside of grave

#### Expected result:

The items from betweenlands should also appear in the graves

#### Actual result:

The items drop onto the ground.

**Comment by pau101** [comment]
Please report pack issues to their curator, (https://github.com/Darkosto/SevTech-Ages/issues). Looking into it though, this is an issue with TombManyGraves as they provide specific support for individual mods (https://github.com/M4thG33k/TombManyGraves2/issues/1) since their implementation made it unnecessarily difficult for compatibility. I'd normally advise using the [GraveStone](https://minecraft.curseforge.com/projects/gravestone-mod) mod as it is implemented elegantly, so you don't experience this issue. But, of course this is the pack. I find it a bit odd this issue with TombManyGraves wasn't caught in testing, it's not exactly an obscure one. Would be very helpful if  TombManyGraves provided an API for offering support for it.

**Comment by 3jlowes** [comment]
Thanks a lot for your reply. I really appreciate this. I will go ahead and submit something to the Sevtech issue tracker. Thanks for explaining why its not something you can fix. I really appreciate the mod and it is easily one of the best for 1.12
