### ISSUE TITLE
When riding a weewood boat water disappears 

### ISSUE THREAD

**Issue by darkphan** [TheCyberBrick/The-Betweenlands#568]
#### Betweenlands version: 

3.3.6

#### Forge version: 

14.23.2.2651

#### Singleplayer or Multiplayer:

Single and Multi 

#### Installed mods:

SevTech

#### How to reproduce:

1. Craft Weedwood Boat
2. Place in water
3. Watch Water Disappear

#### Expected result:

water should not disappear

#### Actual result:

water disappears

#### Pictures:

https://i.imgur.com/uVV4g3I.jpg

**Comment by radfast** [comment]
Hi, Galacticraft dev here.  The same issue is seen when Galacticraft is installed alongside The Betweenlands.

My testing shows the issue was introduced between The Betweenlands versions 3.3.0 (no issue) and 3.3.1 (issue occurs).   For more info please look at the link above.  I don't think this issue is on our side.

**Comment by radfast** [comment]
Possibly caused by this:
https://github.com/Angry-Pixel/The-Betweenlands/commit/728ab7d0116a7de053e84018aa46a6e063b24d14

Generating a `RenderPlayerEvent.Post` from inside the `RenderPlayerEvent.Pre` event doesn't seem like it would be a good idea, because other mods' event handlers (any which come after The Betweenlands) will still be cycling through the `RenderPlayerEvent.Pre` events at this time.  You are forcing other mods to process their `RenderPlayerEvent.Post` handlers before their `RenderPlayerEvent.Pre` handlers have even been called: not good.  You are also probably causing the other mods `RenderPlayerEvent.Post` handlers to be called **twice** as Forge will also fire that post event.

Therefore my guess is the problem will almost certainly be solved if [that line](https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12/src/main/java/thebetweenlands/client/render/entity/RenderWeedwoodRowboat.java#L236) is commented out.

**Comment by pau101** [comment]
I contemplated a lot on how to deal with #511, had a conversation with mezz on events, but ultimately went for the experimental quick fix by firing Post. I'll remove it and correct Erebus.
