### ISSUE TITLE
[1.12.2] Way to the Nether & End

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#595]
The portal tree is great and a nice way to send a player from the Betweenlands to another dimension like the Twilight Forest.  The only issue is that there isn't a way to define multiple dimensions or a good way to get to other places...especially the nether or end.

Is there a way you could add more ways to use the portal tree so that it could go to more places?

**Comment by TheCyberBrick** [comment]
How would that work?

**Comment by TheCyberBrick** [comment]
I'm assuming this is for your modpack so here's a suggestion: I can add a list of block and dimension id pairs config, and depending on which sapling (i.e. aforementioned block) is activated with the Swamp Talisman it would create a portal to the specified dimension. You could then add some craftable or otherwise obtainable saplings with a mod for the nether and end portal

**Comment by MokahTGS** [comment]
Yes, that would be a very flexible way to handle this.  Make the saplings definable in the config and allow us to add new saplings for more dimensions and you have a winner.

**Comment by TheCyberBrick** [comment]
I'm not going to add custom blocks, there are already other mods that do that (Content Tweaker, Custom Stuff, etc.).

**Comment by TheCyberBrick** [comment]
![](https://i.imgur.com/4i5IWdg.png)
![](https://i.imgur.com/Cwr0tSz.png)
![](https://i.imgur.com/MZoheVq.png)
![](https://i.imgur.com/37NPSkn.png)
![](https://i.imgur.com/yonDNoh.png)

Just used obsidian for this example. You could of course create some custom saplings with e.g. Content Tweaker and then configure it to create a portal to the nether.

**Comment by MokahTGS** [comment]
This is absolutely perfect, thank you!
