### ISSUE TITLE
Server crash: stack overflow while updating neighbors (bottle brush grass)

### ISSUE THREAD

**Issue by belathus** [TheCyberBrick/The-Betweenlands#598]
#### Betweenlands version:
3.3.8

#### Forge version:
14.23.3.2655

#### Singleplayer or Multiplayer:
Multiplayer, private server

#### Installed mods:
Modpack: Wanderlust Renewed (not yet released on ATL)
I'll add a list when I am not on my cell phone.

## Link to full crash log
https://gist.github.com/belathus/6efb6c8a8e26b2ed7bba6312120dfdb3

#### How to reproduce:
Not sure, just yet. The server crashes when the player joins. I do not yet know if it would crash when someone else joins. I suspect it happens only in the Betweenlands dimension.

**Comment by TheCyberBrick** [comment]
Could you send me the previous server logs and server crash logs (if there are any) from before this crash?
Did you add/remove mod(s) right before this crash happened?

---
In any case try updating to Forge 14.23.3.2677 or later because a bug was fixed that *might* be related to this. It won't fix this crash though because the damage is already done and the world is corrupted. If it's only happening in the BL you can try deleting the BL world.

**Comment by belathus** [comment]
Yeah, the world was corrupted. I suspect it has something to do with the loot tables I was implementing (though I have no idea why a bad loot table would cause corruption). A different player was able to join the server this morning and basically told me everything was borked. I restored from backup and everything seems fine.

I hadn't added or updated any mods in more than a week. I was only manipulating loot tables and editing recipes. We got crashes with the latest version of Forge, so I went back to the latest recommended version. I'm guessing that since the crash is related to world corruption, the issue probably isn't related to the Betweenlands at all, and you could probably safely close this issue.
