### ISSUE TITLE
Suggestion: Dentrothyst Fragments

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#644]
## Dentrothyst Fragments ![green_dentrothyst_fragment](https://user-images.githubusercontent.com/32495545/41673709-b7fd5588-748b-11e8-8537-6753cf395356.png) ![orange_dentothyst_fragment](https://user-images.githubusercontent.com/32495545/41673727-c6481970-748b-11e8-88b2-eba722f7f478.png)

would be uncommon loot items from Pots of Chance, and possibly chests in certain structures.
**Uncommon** is a word which here means **inbetween rare and common.**
 
The idea is to make herblore less grindy. Nobody wants to spend hours digging through tree stumps just to make potions, so fragments will help with that by allowing you to get dentrothyst through other means.

**Crafting either variant in a 2x2 shape will result in one block of the respective dentrothyst.**

![recipe](https://user-images.githubusercontent.com/32495545/41674074-e302aa52-748c-11e8-9189-f5c1381d96a9.gif)

![not a fake screenshot 1](https://user-images.githubusercontent.com/32495545/41674331-b119dc80-748d-11e8-9f07-8e8318f0f430.png)

Feel free to use the item sprites at the top if you decide to implement this.

**Comment by TheCyberBrick** [comment]
That's a neat idea 👍 
If we add that thrown vials could drop 8-12 shards when they break

**Comment by PetasiGit** [comment]
I hadn't even thought about that, good idea. There's one problem with the number you suggested, though.

The bottle to dentrothyst block ratio is 1:1, as 3 dentrothyst make 3 bottles. Having a single vial drop 4 or more fragments when thrown would allow you to duplicate them. Three would be the maximum amount a thrown vial could drop without allowing you to throw the bottle for no material cost.

**Comment by TripleHeadedSheep** [comment]
Depends if the recipe will be 4 shards for one block or 9 shards for one block. I like the idea, it is something to consider. And it would help with some of the balancing problems we have with loot.

**Comment by PetasiGit** [comment]
With how much dentrothyst is used in herblore, it should probably be four for each block. Since the amount of loot in pots will be drastically decreased, I think it would be balanced at four.

**Comment by TripleHeadedSheep** [comment]
I think that entirely depends on how we balance the loot tables, and how common we make the shards to drop. It might even be a cool mob drop for Pyrad based mobs?

I don't know where you based this on: ' Since the amount of loot in pots will be drastically decreased'
Re-balanced does not always mean decreased. Let alone 'drastically'.

**Comment by PetasiGit** [comment]
It could work, just needs to fit with the **L O R E.**

I don't have any actual proof that you guys have said it, but in the past it was said that pots of chance drop too many items and that it would be decreased quite a bit.

**Comment by TheCyberBrick** [comment]
Or since dentrothyst is quite uncommon we could make the block drop 9 shards when broken and make the dentrothyst vial recipe use 3 shards + 1 solid rubber for one vial. Then, also make smelting liquid rubber give 3 solid rubber, since the rubber harvesting process is quite slow.
Like that we could have thrown vials drop 2-3 shards and at the same time make vials and rubber stuff easier and less grindy to craft.
Edit: Making the dentrothyst block drop 4 shards would also work, then the dentrothyst vial recipe would be just slightly cheaper. Right now it's basically one denthrothyst block per vial.

**Comment by PetasiGit** [comment]
The blocks dropping 4 shards could work too. Ultimately it's up to you guys, just keep balancing in mind. Would pots still drop shards if the block does too? Would you craft dentrothyst panes and alembics with blocks or shards? 


If you'd go with this idea, I think alembics should still be crafted with blocks of dentrothyst. It's only one, after all. As for panes, nobody really uses them to begin with; it could make them easier to craft if they used shards.

**Comment by TripleHeadedSheep** [comment]
I'd prefer shards for vials, but any other recipe involving dentrothyst as we have them should stay the same.
