### ISSUE TITLE
3D models of some BL plants have incorrect lighting effects

### ISSUE THREAD

**Issue by RisingInIris2017** [TheCyberBrick/The-Betweenlands#649]
#### Betweenlands version:

Release 3.3.8

#### Forge version:

14.23.3.2673

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

https://paste.ubuntu.com/p/gXPcBW6TdH/

## Link to full crash log

This bug doesn't crash the game.

#### How to reproduce:

1.plant some BL plants which have 3D models in the ground, such as Weeping Blue, Sundew or Pitcher Plant. 
2. you will find some parts of them are incorrectly dark, just like what these pictures show. 
I have marked them with red circles.

#### Pictures:

![](https://i.paste.pics/ed8697b617a5845758dda7143760d4ef.png?trs=fd0bb0f3dbee25eda1a7cc0e17b00ee31b88bba02def49ef47a78a708c4bd56c)
![](https://i.paste.pics/7d0520d9a37b8b145a72174b1ce22f66.png?trs=fd0bb0f3dbee25eda1a7cc0e17b00ee31b88bba02def49ef47a78a708c4bd56c)

**Comment by TheCyberBrick** [comment]
That's because Optifine disables Forge's improved lighting system. You can temporarily fix it by going into Forge's settings, disable "Client Settings > Forge Light Pipeline Enabled", save, and then enable it again. But that needs to be done everytime you restart the game so it's not really a solution.
