### ISSUE TITLE
make trees and such gen in the BL

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#66]
Sam said we're good to go =)

**Comment by vadis365** [comment]
OK - I'll take a look at implementing some sort of gen tonight.
The smaller trees would be ok to add to the biome decorator as they are smaller than 32x32 in width and depth. an offset will have to be calculated from the largest size it could be otherwise you will get errors for decorating outside of a chunk that hasn't gen'd properly.
The giant trees will have to added to WorldGen because they far exceed the biome decorators capabilities. Could you posibly make a list of other plants gen - like swamp grass and cattails etc. as these can be added quite easily, seeing as the biome decorator will be already needed for the trees.

**Comment by MrCompost** [comment]
Do you want me to just list the very basic plants, or a few others like Swamp Reeds?

**Comment by vadis365** [comment]
Any really - like the ones that act like grass and maybe the double height ones as well ;)
It will make the gen look better with a bit of 'life' in it.

**Comment by MrCompost** [comment]
Sure
