### ISSUE TITLE
Old versions of core mod are left and loaded in the 1.12.2 server folder.

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#660]
#### Betweenlands version:

TheBetweenlands-3.3.10-universal

#### Forge version:

forge-1.12.2-14.23.4.2726-universal

#### Singleplayer or Multiplayer:
Multiplayer 

#### Installed mods:

https://minecraft.curseforge.com/projects/ancient-towncraft/

#### How to reproduce:

After each update the old core mod is still in the folder and getting loaded.

![1c7932776e3d871c52481e9ad64bc4ff](https://user-images.githubusercontent.com/4427684/42333194-50bd1dc4-8037-11e8-8132-8d92f5d9b90b.png)

This was discovered when searching this crash to find the cause, not saying it is related, but I hope it is.

https://gist.github.com/ProsperCraft/e7f92dce039880b4701e877d9398f20f

**Comment by TheCyberBrick** [comment]
The coremod thing is just what Forge's best practices with coremods recommends, the coremod should be in a seperate jar. Hopefully the new mod dependency system that's supposedly coming with Forge 1.13 will fix this problem and take care of outdated coremods. Meanwhile I'll try adding a check that makes outdated coremods not do anything.  
Regarding the crash: It doesn't really look like something caused by the Betweenlands. Is there a specific reason why you think it might be the Betweenlands? Have you tried without the Betweenlands installed, etc.?

**Comment by ProsperCraft** [comment]
I don't suspect The Betweenlands specifically, I just found the multiple coremods when reading that crash report.

Other mods delete their old core mods, perhaps you could have each version do that for The Betweenlands as well?

**Comment by TheCyberBrick** [comment]
>Other mods delete their old core mods, perhaps you could have each version do that for The Betweenlands as well?

Which ones for example? I don't see how the coremods could delete themselves before or after being loaded.

**Comment by TheCyberBrick** [comment]
Looks like Forge now allows specifying a maven version in the coremod, maybe that could fix it.

**Comment by ProsperCraft** [comment]
I may be wrong, but I think Immersive engineering removes their old core mods.

**Comment by TheCyberBrick** [comment]
Ah yeah, IE is using the maven version attribute which fixes this problem:
> - Added support for Forge's memory Maven repo, this makes deleting old coremod versions unnecessary in Forge 2656+ (latest) (Malte)
