### ISSUE TITLE
Infusions always at base stats!

### ISSUE THREAD

**Issue by Emblin13** [TheCyberBrick/The-Betweenlands#667]
#### Betweenlands version:
Version 3.3.8

#### Forge version:
Forge 14.23.4.2707

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Mod list: https://sevtechages.gamepedia.com/Mod_List
Modpack: https://minecraft.curseforge.com/projects/sevtech-ages

#### How to reproduce:
1    Find an infusion recipe to make
2    Get the appropriate vials of essence to make it
3    Put the vials of essence into a water filled infuser (the amount of essences doesn't seem to matter)
4    Stir the infuser until it gives an audio cue and changes color
5    Shift right-click the infuser with a bucket, and pour it into an alembic
6    Let the alembic finish processing the infusion
7    Retrieve the infusion with a dentrothyst vial
8    Watch in despair as you get infusions with potency 1, duration 1, regardless of what you do.

#### Expected result:
I should get an infusion with potency and duration which match the amount of essence I used. For example, when I try to make a healing elixir, I use 3 yeowynn and 3 ordaniis, and I should be getting a healing elixir with potency of 3, duration of 3.

#### Actual result:
Regardless of how much essence I use, and regardless of the ratios, I seem to only get infusions with potency 1, duration 1.

**Comment by monodemono** [comment]
Unable to replicate...

<img width="1920" alt="screen shot 2018-07-20 at 17 35 07" src="https://user-images.githubusercontent.com/1161277/43030295-47bbd770-8c43-11e8-88f7-f13c814d02e3.png">
<img width="1920" alt="screen shot 2018-07-20 at 17 35 09" src="https://user-images.githubusercontent.com/1161277/43030298-49dea1fe-8c43-11e8-8130-7f1db9513fae.png">

**Comment by PetasiGit** [comment]
You need to use 3 full vials of Yeowynn and 3 full vials of Ordaniis if you want to max out the stats. A full vials holds 5 of an aspect amount. Fill 3 vials of each to 5 aspect value and try them.

**Comment by TheCyberBrick** [comment]
The potency and duration is calculated from the ratios of the contained aspects. It's not ideal right now and I'd like to change and rebalance it at some point

**Comment by alxcool** [comment]
Oh ratio^^ I was like... lately for a Brew of the Cat eye, I've used 12.0 of Dayuniis, with 1.0 of Ordaniis. The two others Freiwynn, and Geoliirgaz was also at 1.0. Result Lv I/II (or 2.25) Potion last 4:40 instead of 2:30.
If I want to increase potion potently without using more than 15.0 Dayuniis, would it help if others elements was at 5.0? I know that more secondary product I use, more potions per bucket I could recover... Once I've earned 12 Potion Lv 1/1

For now the most efficient recipe for a night vision potion is 0.11 in every stats as it lend a minimum potion effect with 1 potion per buckets.

**Comment by kinazarov** [comment]
Same issue here: I used 1 vial of 5.0 yeowynn and 1 vial of 1.0 ordaniis. expected healing 5 with some small effect duration but i recieve tier 1 potency and tier 1 duration

**Comment by PetasiGit** [comment]
Duration and potency are based on the amount of full vials/multiples of 5.0 aspect. A vial of 5.0 amounts to a one level change in potency/duration, but note that smaller amounts still have an effect on duration (but not potency, it seems). Closing because it was a misunderstanding of how herblore works.
