### ISSUE TITLE
[1.12.2] Client Hooks Crash

### ISSUE THREAD

**Issue by Yhuxz** [TheCyberBrick/The-Betweenlands#699]
I just tried the mod because of watching sevtech game plays, never knew that this mod is heavy on ram so i removed it (I only have 4gb ram) tried to play without it, but every time it crashes. 

It works if the mod is installed by itself and with other mods I use but not without it.
Now I can't play modded without having the mod installed

Crashlog:
[crash-2018-09-01_09.29.41-client.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2341964/crash-2018-09-01_09.29.41-client.txt)

**Comment by pau101** [comment]
Thanks for the report! Delete `TheBetweenlands-3.3.10-core.jar` from your `mods/` directory and update to version [3.3.11](https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2594647) of The Betweenlands if you wish to continue play, as it includes the fix for this issue.

**Comment by Yhuxz** [comment]
Ahh I see I didn't know the core is in the mods/1.12.2 folder I only saw the other files in mods/memory_repo folder

If I have a chance to upgrade my ram I might try to add this again thanks for the reply and sorry for not following the template
