### ISSUE TITLE
Minecraft Failed To Start with Survival Technician 2 modpack.

### ISSUE THREAD

**Issue by Onikage056** [TheCyberBrick/The-Betweenlands#757]
#### Betweenlands version:
3.4.0-universal

#### Forge version:
1.12.2-2.6.0.79-universal

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Technician's Survival 2 modpack

## Link to full crash log
https://paste.dimdev.org/cihejadiwa.mccrash

#### How to reproduce:
1. Start Minecraft
2. Crash

#### Expected result:
I expected the modpack to actually start so I could try it out.

#### Actual result:
The game crashed without even starting.

Modpack Link from Curse Forge: https://minecraft.curseforge.com/projects/technicians-survival-2

**Comment by TheCyberBrick** [comment]
Installed the pack and it's working without any problems.
Make sure everything is installed correctly, e.g. try reinstalling the pack.
I've also heard that installing modpacks in OneDrive can cause problems, so if you're doing that install the pack somewhere else.

**Comment by Onikage056** [comment]
Maybe it's because of the Twitch launcher...
because I just got this when I tried: https://paste.dimdev.org/wuzebixire.mccrash

**Comment by TheCyberBrick** [comment]
Probably not, I installed it using the Twitch launcher.
Did you reinstall the pack like I suggested? Did you manually modify any of the downloaded files?
Also, please post the whole log so I can have a look at it.

**Comment by Onikage056** [comment]
I reinstalled as suggested, modified nothing, and... There... the entire crash log.

Edit:
https://hastebin.com/cowugebuko.rb

**Comment by GoryMoon** [comment]
Can you upload the `debug.log` that you can find in the `logs` folder in the modpack instance?

**Comment by Onikage056** [comment]
[latest.log](https://github.com/Angry-Pixel/The-Betweenlands/files/2552406/latest.log)

That's the only log in the folder.

**Comment by GoryMoon** [comment]
Do you have multiple instances running of the pack or some other program that would interfere?
Try restarting the twitch launcher (right click, Quit or Exit or whatever it is), make sure no process is running (with for example Task Manager).
If that doesn't work I'm not sure what's the cause, possible very long fetched but maybe restart the computer if you haven't (don't think it matters but you never know)?

Because from the looks of it in that last log file some other process is using the file need to load and preventing forge to get access to it. Also from the looks of it `ImmersiveEngineering` would be affected in-game if it would boot as it's also being denied loading of its core.

**Comment by Onikage056** [comment]
No, I've never run multiple instances of Minecraft, modded or not. And I've rebooted twice since this started with no luck.

Well... dunno how it happened, but another attempt got past the initialization phase... then crashed.
Attaching crash log...
[crash log.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2553849/crash.log.txt)

**Comment by GoryMoon** [comment]
That crash is of Java itself and not minecraft directly. Looks like foamfix is part of the issue or just a false positive.
Try updating to the latest Java 1.8 (1.8 Update 191).
Other than that I don't know what could have caused it.

**Comment by Onikage056** [comment]
That did it. Got it running after updating Java. It's slow to load, which isn't surprising given the mod count, but it's working.

Thanks for your help. :)
