### ISSUE TITLE
Incompatible with Tick Dynamic

### ISSUE THREAD

**Issue by Sunconure11** [TheCyberBrick/The-Betweenlands#815]
Server crashed with this error, seems to be a conflict between the two mods:

https://pastebin.com/Eew8TP5Y

**Comment by theishiopian** [comment]
I'd recommend reporting this to Tick Dynamics' [github](https://github.com/The-Fireplace-Minecraft-Mods/TickDynamic/issues), since this probably isnt a thing that the BL team has control over.

**Comment by Sunconure11** [comment]
Dev stopped working on TD.

**Comment by OuiGH** [comment]
I also have this issue in sevtech which i added tickdynamic to.

**Comment by pau101** [comment]
Thanks for reporting, and apologies for late response!

This crash appears to be entirely on Tick Dynamic's end, however this is incidentally already fixed with some code changes unrelated to this specific issue in our latest release.

Also, we do not advise adding additional mods to mod packs, especially an invasive one like Tick Dynamic.

**Comment by Sunconure11** [comment]
I'm the maker of said pack. I was looking into it at the time to reduce some TPS lag.

**Comment by pau101** [comment]
Ah I see, that is understandable.
