### ISSUE TITLE
[Small Suggestion] Greebling Naming

### ISSUE THREAD

**Issue by aycfes** [TheCyberBrick/The-Betweenlands#833]
simple, if you manage to name a greebing with a name tag, instead of permanently disappearing when you get close, they'd only do so momentarily, appearing again either at the same spot, or elsewhere nearby

**Comment by archynoid** [comment]
I for one would personally love to see this, mainly due to all the lack of interactions we can have with a greebling for one. They aren't _toooo_ common is another. Plus it would be kind of neat to kind of show off a bit of progression in the betweens lands with making like a little band or something like that.

**Comment by TheCyberBrick** [comment]
There are other types of greeblings planned to be added in the future. I'm not going to spoil much but the Greeblings will be more fleshed out and have interesting interactions (you'll see... :p) once we have time to work on them. IIRC we even had a protoype back in 1.7.10 that was never added... ;)
