### ISSUE TITLE
Image Freezing

### ISSUE THREAD

**Issue by PresquePlayed** [TheCyberBrick/The-Betweenlands#835]
#### Betweenlands version:

v.3.4.7

#### Forge version:

1.12.2forge- 14.23.5.2838 (latest)

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

Betweenlands + Optifine with Sildur Vibrant 1.18 VL shader

## Link to full crash log

MC doesnt crash really but you have to restart it

#### How to reproduce:

1. Install betweenlands and Optifine
2. Activate Sildur Vibrant 1.18 VL shader (possibly other shaders wont work too I didnt test it)
3. enter betweenlands or use the shock wave ability of the shockwave sword

#### Expected result:

Entering the Betweenlands / causing a shock wave

#### Actual result:

The image of MC will freeze if you press Esc you can see your mouse and move it. It is also possible to hear sounds fro MC but the Image is stuck

**Comment by GoryMoon** [comment]
This is a known incompatibility with Optifine using shaders.
The Betweenlands have its own shaders and because of that breaking when using Optifines shaders.
You can either not use Optifine Shaders or disable The Betweenlands shaders in our config, doing that will result in missing effects in The Betweenlands.
