### ISSUE TITLE
Crash when Little Maids kill mobs while Betweenlands is installed

### ISSUE THREAD

**Issue by ConcernedNEET** [TheCyberBrick/The-Betweenlands#842]
#### Betweenlands version:

Tested on 1.4.9/1.4.8

#### Forge version:

14.23.5.2838

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

[1.12.2]EBLib-6.1.6.9-peko_build
[1.12.2]LittleMaidReengaged-8.1.6.141-peko_build-1.1.1
jei_1.12.2-4.14.4.264
OptiFine_1.12.2_HD_U_E3 
TheBetweenlands-3.4.9-universal 

## Link to full crash log

https://pastebin.com/4QQirSBr

## Description of the problem
While Betweenlands is installed, the game will crash when maids from the LittleMaidMob mod kill any mob (not just Betweenlands mobs) with a melee attack. For some reason this only happens when Betweenlands is installed, even if the maid is fighting a vanilla mob in the overworld. I've toggled every option in the Betweenlands config that I can, but it doesn't help. Tried with both the Peko build and the current files on https://minecraft.curseforge.com/projects/littlemaidmobx
#### How to reproduce:

1. Give a maid a cake to recruit it.
2. Equip any sword in its main hand.
3. Let it fight a mob.

#### Expected result:

The mob dies and drops its item, the game continues as normal.

#### Actual result:

When the mob dies, the game freezes for a moment and then crashes.

**Comment by TheCyberBrick** [comment]
Hi, I've found some errors that might be related to this. Please try with this dev build https://github.com/Angry-Pixel/The-Betweenlands-Development-Builds/releases/tag/dev-1.12-fixes-1734-20.06.2019 and let me know whether that fixes the problem. Thanks.

**Comment by ConcernedNEET** [comment]
Hi, I'm sorry, I've played around with the dev build a bit, but it seems to give the same kind of error. Here's the current crash log. https://pastebin.com/yTGG9QUP
But thank you!

**Comment by GoryMoon** [comment]
This is an issue the Little Maids mod, this is not caused by The Beweenlands it's only that we use more complex advancements then what others use.

I tested with a custom advancement added the vanilla way and it still crashes.
This advancement checks what the attacker killed the entity with, in the test case it's just a diamond sword. We have it for our swords
Placing the folder in the provided zip in `saves/<world_name>/data/advancements/` allows for testing this issue.
[maid_test.zip](https://github.com/Angry-Pixel/The-Betweenlands/files/3314256/maid_test.zip)

**Comment by GoryMoon** [comment]
This is an issue in the LittleMaid mod, this isn't caused by The Betweenlands other than the more advanced advancements that we use. We have some advancements checking what weapon that was used to kill an entity and that causes the issue.

You can trigger this issue by creating a custom advancement, I provided on in the zip below.
I tested this with only the maid mod and its library mod.
Extract the folder in the zip and place the folder in the `saves/<world name>/data/advancements/` folder, then load the world and let a maid kill an entity.
Maid test advancement: [maid_test.zip](https://github.com/Angry-Pixel/The-Betweenlands/files/3314357/maid_test.zip)

**Comment by TheCyberBrick** [comment]
Ah, thanks Gory! I only looked at the ClassCastException and assumed it to be the typical datawatcher error :P

**Comment by ConcernedNEET** [comment]
Ah, that's a shame. In that case, I'm gonna close this now. Thanks guys.

**Comment by GoryMoon** [comment]
You can/should report this to their issue tracker so it can be fixed.
