### ISSUE TITLE
Mod crash while starting Roguelike Adventures and Dungeons

### ISSUE THREAD

**Issue by Grappson** [TheCyberBrick/The-Betweenlands#883]
#### Betweenlands version:

3.4.11

#### Forge version:

14.23.5.2838

#### Singleplayer or Multiplayer:

single player

#### Installed mods:

Roguelike Adventures and Dungeons (version 1.31)

## Link to full crash log

https://paste.dimdev.org/irerorilon.mccrash

#### How to reproduce:

1.Start the minecraft from launcher
2.crash
3. etc...

#### Expected result:

Crash

#### Actual result:

Crash

**Comment by theishiopian** [comment]
You expected a crash?

**Comment by Grappson** [comment]
Secone time I did, not firat

**Comment by Grappson** [comment]
First*

**Comment by TheCyberBrick** [comment]
This happens when Forge can't extract our coremod which we can't do anything about. I think this is most likely a permission issue, so make sure your mods are in a folder that Forge has permission to write files to.
If I remember correctly, somebody had a similar problem when the mod was installed on OneDrive.
