### ISSUE TITLE
Missing registry conflict due to FastFurnace

### ISSUE THREAD

**Issue by Cynosphere** [TheCyberBrick/The-Betweenlands#986]
`Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:furnace (thebetweenlands.common.recipe.ShapelessOverrideDummyRecipe$ShapedOverrideDummyRecipe@3c46fc9) produces unregistered item minecraft:furnace (net.minecraft.item.ItemBlock@4d964c9e)`
and
`[Netty Client IO #1/FATAL] [FML]: Failed to connect to server: there are 2 missing registry items`

Only one person on my server so far has had this issue and I haven't been able to find ways to reproduce it yet but it's pretty much softlocked the person out of my server somehow

Betweenlands 3.5.6, Forge 2847, FastFurnace 1.3.1, [All other mods](https://gist.github.com/Cynosphere/2c87d8b4034e95e8418369290c2a0769)

**Comment by TheCyberBrick** [comment]
Hi, please make sure the list of mods and all mod configs are identical on client and server. Since this is only happening to one person it's likely a configuration problem or difference in mods.  
If all fails you can disable "Override Any Conflicting Oredict Recipes" and "Override Conflicting Vanilla Oredict Recipes" in the Betweenlands config (both on server and clients). That however may cause some Betweenlands recipes to not work properly and need manual fixing (e.g. with CraftTweaker).
