### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#995]
Forge x.2847
Betweenlands 3.5.7

https://paste.dimdev.org/awujehubam.mccrash

Edit: the previous version (3.5.6) with no other changes doesn't have the issue.

Redirect if needed.

**Comment by ProsperCraft** [comment]
Same crash--https://paste.dimdev.org/wizagehaqo.mccrash

modpack .98-https://www.curseforge.com/minecraft/modpacks/ancient-towncraft/

TheBetweenlands-3.5.7-universal

**Comment by TheCyberBrick** [comment]
I can't reproduce this. Ancient Towncraft 0.98 loads just fine for me.  
Please check the mods folder and confirm that "mods/memory_repo/angrypixel/TheBetweenlands/3.5.7/TheBetweenlands-3.5.7-core.jar" exists.
If that file does not exist then Forge has failed to extract that file properly. Perhaps running out of space or unable to write the file due to lacking permission, or an anti-virus program false positive? Please upload the logs and/or check them for errors.    
Either way this does not seem like a problem on our side because between 3.5.6 and 3.5.7 not much has changed, and especially nothing of the core mod.

**Comment by ghost** [comment]
While I cannot speak to the above modpack, I can confirm that in mine it is extracting it properly.

Which log files would you like specifically?

And while not much has changed, switching between the two versions of this mod, while changing absolutely nothing else, DOES have a change, either with this mod or interaction with/from another mod. If it is another mod, I do not posses the programming ability to decipher the crash reports further, and will require assistance.

**Comment by TheCyberBrick** [comment]
debug.log and latest.log

**Comment by ghost** [comment]
And of course Minecraft is being a troll and won't crash now -.- . I'll update this when it happens again.

**Comment by TheCyberBrick** [comment]
I can't help further help here without the logs.
If this resolved itself, great 👍
